//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 6/28/2016 2:14:03 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.Diagnosis in the schema.
    /// </summary>
    [Table(Name = @"public.diagnosis")]
    public partial class Diagnosis : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private string _EmrIdentifier;

        private string _ShortDescription;

        private string _LongDescription;

        private CodedEntry _DiagCode;

        private System.Nullable<System.DateTime> _DeterminationDateTime;

        private System.Nullable<System.DateTime> _StartDateTime;

        private System.Nullable<System.DateTime> _EndDateTime;

        private string _Status;

        private System.Nullable<System.DateTime> _StatusDateTime;

        private long _Patientdbid;

        private System.Nullable<long> _VisitEncounterdbid;
        #pragma warning restore 0649

        private EntityRef<Patient> _Patient;

        private EntityRef<VisitEncounter> _VisitEncounter;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnEmrIdentifierChanging(string value);
        partial void OnEmrIdentifierChanged();
        partial void OnShortDescriptionChanging(string value);
        partial void OnShortDescriptionChanged();
        partial void OnLongDescriptionChanging(string value);
        partial void OnLongDescriptionChanged();
        partial void OnDiagCodeChanging(CodedEntry value);
        partial void OnDiagCodeChanged();
        partial void OnDeterminationDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnDeterminationDateTimeChanged();
        partial void OnStartDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnStartDateTimeChanged();
        partial void OnEndDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnEndDateTimeChanged();
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        partial void OnStatusDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnStatusDateTimeChanged();
        partial void OnPatientdbidChanging(long value);
        partial void OnPatientdbidChanged();
        partial void OnVisitEncounterdbidChanging(System.Nullable<long> value);
        partial void OnVisitEncounterdbidChanged();
        #endregion

        public Diagnosis()
        {
            this._DiagCode = new CodedEntry();
            this._Patient  = default(EntityRef<Patient>);
            this._VisitEncounter  = default(EntityRef<VisitEncounter>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for EmrIdentifier in the schema.
        /// </summary>
        [Column(Name = @"emridentifier", Storage = "_EmrIdentifier", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string EmrIdentifier
        {
            get
            {
                return this._EmrIdentifier;
            }
            set
            {
                if (this._EmrIdentifier != value)
                {
                    this.OnEmrIdentifierChanging(value);
                    this.SendPropertyChanging();
                    this._EmrIdentifier = value;
                    this.SendPropertyChanged("EmrIdentifier");
                    this.OnEmrIdentifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ShortDescription in the schema.
        /// </summary>
        [Column(Name = @"shortdescription", Storage = "_ShortDescription", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string ShortDescription
        {
            get
            {
                return this._ShortDescription;
            }
            set
            {
                if (this._ShortDescription != value)
                {
                    this.OnShortDescriptionChanging(value);
                    this.SendPropertyChanging();
                    this._ShortDescription = value;
                    this.SendPropertyChanged("ShortDescription");
                    this.OnShortDescriptionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for LongDescription in the schema.
        /// </summary>
        [Column(Name = @"longdescription", Storage = "_LongDescription", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string LongDescription
        {
            get
            {
                return this._LongDescription;
            }
            set
            {
                if (this._LongDescription != value)
                {
                    this.OnLongDescriptionChanging(value);
                    this.SendPropertyChanging();
                    this._LongDescription = value;
                    this.SendPropertyChanged("LongDescription");
                    this.OnLongDescriptionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DiagCode in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.ValueTypeProperty()]
        [Devart.Data.Linq.Mapping.Column(Member = "Code", Name = @"code", Storage = "_Code", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystem", Name = @"codesystem", Storage = "_CodeSystem", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystemVersion", Name = @"codesystemversion", Storage = "_CodeSystemVersion", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeMeaning", Name = @"codemeaning", Storage = "_CodeMeaning", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeModifier", Name = @"codemodifier", Storage = "_CodeModifier", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeModifierDescription", Name = @"codemodifierdescription", Storage = "_CodeModifierDescription", DbType = "varchar")]
        public CodedEntry DiagCode
        {
            get
            {
                return this._DiagCode;
            }
            set
            {
                if (this._DiagCode != value)
                {
                    this.OnDiagCodeChanging(value);
                    this.SendPropertyChanging();
                    this._DiagCode = value;
                    this.SendPropertyChanged("DiagCode");
                    this.OnDiagCodeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DeterminationDateTime in the schema.
        /// </summary>
        [Column(Name = @"determinationdatetime", Storage = "_DeterminationDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> DeterminationDateTime
        {
            get
            {
                return this._DeterminationDateTime;
            }
            set
            {
                if (this._DeterminationDateTime != value)
                {
                    this.OnDeterminationDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._DeterminationDateTime = value;
                    this.SendPropertyChanged("DeterminationDateTime");
                    this.OnDeterminationDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for StartDateTime in the schema.
        /// </summary>
        [Column(Name = @"startdatetime", Storage = "_StartDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> StartDateTime
        {
            get
            {
                return this._StartDateTime;
            }
            set
            {
                if (this._StartDateTime != value)
                {
                    this.OnStartDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._StartDateTime = value;
                    this.SendPropertyChanged("StartDateTime");
                    this.OnStartDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EndDateTime in the schema.
        /// </summary>
        [Column(Name = @"enddatetime", Storage = "_EndDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> EndDateTime
        {
            get
            {
                return this._EndDateTime;
            }
            set
            {
                if (this._EndDateTime != value)
                {
                    this.OnEndDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._EndDateTime = value;
                    this.SendPropertyChanged("EndDateTime");
                    this.OnEndDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        [Column(Name = @"status", Storage = "_Status", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                if (this._Status != value)
                {
                    this.OnStatusChanging(value);
                    this.SendPropertyChanging();
                    this._Status = value;
                    this.SendPropertyChanged("Status");
                    this.OnStatusChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for StatusDateTime in the schema.
        /// </summary>
        [Column(Name = @"statusdatetime", Storage = "_StatusDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> StatusDateTime
        {
            get
            {
                return this._StatusDateTime;
            }
            set
            {
                if (this._StatusDateTime != value)
                {
                    this.OnStatusDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._StatusDateTime = value;
                    this.SendPropertyChanged("StatusDateTime");
                    this.OnStatusDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patientdbid in the schema.
        /// </summary>
        [Column(Name = @"patientdbid", Storage = "_Patientdbid", CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Patientdbid
        {
            get
            {
                return this._Patientdbid;
            }
            set
            {
                if (this._Patientdbid != value)
                {
                    if (this._Patient.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnPatientdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Patientdbid = value;
                    this.SendPropertyChanged("Patientdbid");
                    this.OnPatientdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounterdbid in the schema.
        /// </summary>
        [Column(Name = @"visitencounterdbid", Storage = "_VisitEncounterdbid", DbType = "int8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> VisitEncounterdbid
        {
            get
            {
                return this._VisitEncounterdbid;
            }
            set
            {
                if (this._VisitEncounterdbid != value)
                {
                    if (this._VisitEncounter.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnVisitEncounterdbidChanging(value);
                    this.SendPropertyChanging();
                    this._VisitEncounterdbid = value;
                    this.SendPropertyChanged("VisitEncounterdbid");
                    this.OnVisitEncounterdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Diagnosis", Storage="_Patient", ThisKey="Patientdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Patient Patient
        {
            get
            {
                return this._Patient.Entity;
            }
            set
            {
                Patient previousValue = this._Patient.Entity;
                if ((previousValue != value) || (this._Patient.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Patient.Entity = null;
                        previousValue.Diagnoses.Remove(this);
                    }
                    this._Patient.Entity = value;
                    if (value != null)
                    {
                        this._Patientdbid = value.dbid;
                        value.Diagnoses.Add(this);
                    }
                    else
                    {
                        this._Patientdbid = default(long);
                    }
                    this.SendPropertyChanged("Patient");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounter in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Diagnosis", Storage="_VisitEncounter", ThisKey="VisitEncounterdbid", OtherKey="dbid", IsForeignKey=true)]
        public VisitEncounter VisitEncounter
        {
            get
            {
                return this._VisitEncounter.Entity;
            }
            set
            {
                VisitEncounter previousValue = this._VisitEncounter.Entity;
                if ((previousValue != value) || (this._VisitEncounter.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._VisitEncounter.Entity = null;
                        previousValue.Diagnoses.Remove(this);
                    }
                    this._VisitEncounter.Entity = value;
                    if (value != null)
                    {
                        this._VisitEncounterdbid = value.dbid;
                        value.Diagnoses.Add(this);
                    }
                    else
                    {
                        this._VisitEncounterdbid = default(System.Nullable<long>);
                    }
                    this.SendPropertyChanged("VisitEncounter");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
