//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 5/23/2016 11:42:39 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for Address in the schema.
    /// </summary>
    public partial class Address: INotifyPropertyChanging, INotifyPropertyChanged    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private string _City;

        private string _State;

        private string _PostalCode;

        private string _Country;

        private string _Line1;

        private string _Line2;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        partial void OnLine1Changing(string value);
        partial void OnLine1Changed();
        partial void OnLine2Changing(string value);
        partial void OnLine2Changed();
        #endregion

        public Address()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        [Column(Name = @"city", Storage = "_City", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                if (this._City != value)
                {
                    this.OnCityChanging(value);
                    this.SendPropertyChanging();
                    this._City = value;
                    this.SendPropertyChanged("City");
                    this.OnCityChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for State in the schema.
        /// </summary>
        [Column(Name = @"""state""", Storage = "_State", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                if (this._State != value)
                {
                    this.OnStateChanging(value);
                    this.SendPropertyChanging();
                    this._State = value;
                    this.SendPropertyChanged("State");
                    this.OnStateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PostalCode in the schema.
        /// </summary>
        [Column(Name = @"postalcode", Storage = "_PostalCode", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                if (this._PostalCode != value)
                {
                    this.OnPostalCodeChanging(value);
                    this.SendPropertyChanging();
                    this._PostalCode = value;
                    this.SendPropertyChanged("PostalCode");
                    this.OnPostalCodeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Country in the schema.
        /// </summary>
        [Column(Name = @"country", Storage = "_Country", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                if (this._Country != value)
                {
                    this.OnCountryChanging(value);
                    this.SendPropertyChanging();
                    this._Country = value;
                    this.SendPropertyChanged("Country");
                    this.OnCountryChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Line1 in the schema.
        /// </summary>
        [Column(Name = @"line1", Storage = "_Line1", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Line1
        {
            get
            {
                return this._Line1;
            }
            set
            {
                if (this._Line1 != value)
                {
                    this.OnLine1Changing(value);
                    this.SendPropertyChanging();
                    this._Line1 = value;
                    this.SendPropertyChanged("Line1");
                    this.OnLine1Changed();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Line2 in the schema.
        /// </summary>
        [Column(Name = @"line2", Storage = "_Line2", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Line2
        {
            get
            {
                return this._Line2;
            }
            set
            {
                if (this._Line2 != value)
                {
                    this.OnLine2Changing(value);
                    this.SendPropertyChanging();
                    this._Line2 = value;
                    this.SendPropertyChanged("Line2");
                    this.OnLine2Changed();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
