//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 3/21/2016 10:57:53 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.Charge in the schema.
    /// </summary>
    [Table(Name = @"public.charge")]
    public partial class Charge : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private string _EmrIdentifier;

        private CodedEntry _ChargeCode;

        private string _Description;

        private string _Comment;

        private System.Nullable<System.DateTimeOffset> _DateOfService;

        private System.Nullable<System.DateTimeOffset> _SubmittedDate;

        private string _Sumbitter;

        private System.Nullable<System.DateTimeOffset> _DateInfoLastUpdated;

        private string _Status;

        private DentalDetail _DentalDetails;

        private System.Nullable<long> _VisitEncounterdbid;
        #pragma warning restore 0649

        private EntityRef<VisitEncounter> _VisitEncounter;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnEmrIdentifierChanging(string value);
        partial void OnEmrIdentifierChanged();
        partial void OnChargeCodeChanging(CodedEntry value);
        partial void OnChargeCodeChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        partial void OnDateOfServiceChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnDateOfServiceChanged();
        partial void OnSubmittedDateChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnSubmittedDateChanged();
        partial void OnSumbitterChanging(string value);
        partial void OnSumbitterChanged();
        partial void OnDateInfoLastUpdatedChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnDateInfoLastUpdatedChanged();
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        partial void OnDentalDetailsChanging(DentalDetail value);
        partial void OnDentalDetailsChanged();
        partial void OnVisitEncounterdbidChanging(System.Nullable<long> value);
        partial void OnVisitEncounterdbidChanged();
        #endregion

        public Charge()
        {
            this._ChargeCode = new CodedEntry();
            this._DentalDetails = new DentalDetail();
            this._VisitEncounter  = default(EntityRef<VisitEncounter>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for EmrIdentifier in the schema.
        /// </summary>
        [Column(Name = @"emridentifier", Storage = "_EmrIdentifier", AutoSync = AutoSync.Always, DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string EmrIdentifier
        {
            get
            {
                return this._EmrIdentifier;
            }
            set
            {
                if (this._EmrIdentifier != value)
                {
                    this.OnEmrIdentifierChanging(value);
                    this.SendPropertyChanging();
                    this._EmrIdentifier = value;
                    this.SendPropertyChanged("EmrIdentifier");
                    this.OnEmrIdentifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ChargeCode in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.ValueTypeProperty()]
        [Devart.Data.Linq.Mapping.Column(Member = "Code", Name = @"code", Storage = "_Code", DbType = "varchar NOT NULL")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystem", Name = @"codesystem", Storage = "_CodeSystem", DbType = "varchar NOT NULL")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystemVersion", Name = @"codesystemversion", Storage = "_CodeSystemVersion", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeMeaning", Name = @"codemeaning", Storage = "_CodeMeaning", DbType = "varchar")]
        public CodedEntry ChargeCode
        {
            get
            {
                return this._ChargeCode;
            }
            set
            {
                if (this._ChargeCode != value)
                {
                    this.OnChargeCodeChanging(value);
                    this.SendPropertyChanging();
                    this._ChargeCode = value;
                    this.SendPropertyChanged("ChargeCode");
                    this.OnChargeCodeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        [Column(Name = @"description", Storage = "_Description", AutoSync = AutoSync.Always, DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if (this._Description != value)
                {
                    this.OnDescriptionChanging(value);
                    this.SendPropertyChanging();
                    this._Description = value;
                    this.SendPropertyChanged("Description");
                    this.OnDescriptionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Comment in the schema.
        /// </summary>
        [Column(Name = @"comment", Storage = "_Comment", AutoSync = AutoSync.Always, DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                if (this._Comment != value)
                {
                    this.OnCommentChanging(value);
                    this.SendPropertyChanging();
                    this._Comment = value;
                    this.SendPropertyChanged("Comment");
                    this.OnCommentChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DateOfService in the schema.
        /// </summary>
        [Column(Name = @"dateofservice", Storage = "_DateOfService", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> DateOfService
        {
            get
            {
                return this._DateOfService;
            }
            set
            {
                if (this._DateOfService != value)
                {
                    this.OnDateOfServiceChanging(value);
                    this.SendPropertyChanging();
                    this._DateOfService = value;
                    this.SendPropertyChanged("DateOfService");
                    this.OnDateOfServiceChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for SubmittedDate in the schema.
        /// </summary>
        [Column(Name = @"submitteddate", Storage = "_SubmittedDate", AutoSync = AutoSync.Always, DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> SubmittedDate
        {
            get
            {
                return this._SubmittedDate;
            }
            set
            {
                if (this._SubmittedDate != value)
                {
                    this.OnSubmittedDateChanging(value);
                    this.SendPropertyChanging();
                    this._SubmittedDate = value;
                    this.SendPropertyChanged("SubmittedDate");
                    this.OnSubmittedDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Sumbitter in the schema.
        /// </summary>
        [Column(Name = @"sumbitter", Storage = "_Sumbitter", AutoSync = AutoSync.Always, DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Sumbitter
        {
            get
            {
                return this._Sumbitter;
            }
            set
            {
                if (this._Sumbitter != value)
                {
                    this.OnSumbitterChanging(value);
                    this.SendPropertyChanging();
                    this._Sumbitter = value;
                    this.SendPropertyChanged("Sumbitter");
                    this.OnSumbitterChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DateInfoLastUpdated in the schema.
        /// </summary>
        [Column(Name = @"dateinfolastupdated", Storage = "_DateInfoLastUpdated", AutoSync = AutoSync.Always, DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> DateInfoLastUpdated
        {
            get
            {
                return this._DateInfoLastUpdated;
            }
            set
            {
                if (this._DateInfoLastUpdated != value)
                {
                    this.OnDateInfoLastUpdatedChanging(value);
                    this.SendPropertyChanging();
                    this._DateInfoLastUpdated = value;
                    this.SendPropertyChanged("DateInfoLastUpdated");
                    this.OnDateInfoLastUpdatedChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        [Column(Name = @"status", Storage = "_Status", AutoSync = AutoSync.Always, DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                if (this._Status != value)
                {
                    this.OnStatusChanging(value);
                    this.SendPropertyChanging();
                    this._Status = value;
                    this.SendPropertyChanged("Status");
                    this.OnStatusChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DentalDetails in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.ValueTypeProperty()]
        [Devart.Data.Linq.Mapping.Column(Member = "ToothNumber", Name = @"toothnumber", Storage = "_ToothNumber", DbType = "smallint")]
        [Devart.Data.Linq.Mapping.Column(Member = "ToothSurfaceCode", Name = @"toothsurfacecode", Storage = "_ToothSurfaceCode", DbType = "varchar")]
        public DentalDetail DentalDetails
        {
            get
            {
                return this._DentalDetails;
            }
            set
            {
                if (this._DentalDetails != value)
                {
                    this.OnDentalDetailsChanging(value);
                    this.SendPropertyChanging();
                    this._DentalDetails = value;
                    this.SendPropertyChanged("DentalDetails");
                    this.OnDentalDetailsChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounterdbid in the schema.
        /// </summary>
        [Column(Name = @"visitencounterdbid", Storage = "_VisitEncounterdbid", DbType = "int8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> VisitEncounterdbid
        {
            get
            {
                return this._VisitEncounterdbid;
            }
            set
            {
                if (this._VisitEncounterdbid != value)
                {
                    if (this._VisitEncounter.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnVisitEncounterdbidChanging(value);
                    this.SendPropertyChanging();
                    this._VisitEncounterdbid = value;
                    this.SendPropertyChanged("VisitEncounterdbid");
                    this.OnVisitEncounterdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounter in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Charge", Storage="_VisitEncounter", ThisKey="VisitEncounterdbid", OtherKey="dbid", IsForeignKey=true)]
        public VisitEncounter VisitEncounter
        {
            get
            {
                return this._VisitEncounter.Entity;
            }
            set
            {
                VisitEncounter previousValue = this._VisitEncounter.Entity;
                if ((previousValue != value) || (this._VisitEncounter.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._VisitEncounter.Entity = null;
                        previousValue.Charges.Remove(this);
                    }
                    this._VisitEncounter.Entity = value;
                    if (value != null)
                    {
                        this._VisitEncounterdbid = value.dbid;
                        value.Charges.Add(this);
                    }
                    else
                    {
                        this._VisitEncounterdbid = default(System.Nullable<long>);
                    }
                    this.SendPropertyChanged("VisitEncounter");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
