//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 6/28/2016 8:49:38 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for AggregationRunStatus in the schema.
    /// </summary>
    [Flags]
    public enum AggregationRunStatus : int
    {
    
        /// <summary>
        /// There are no comments for AggregationRunStatus.RunNumberReserved in the schema.
        /// </summary>
        RunNumberReserved = 1,    
        /// <summary>
        /// There are no comments for AggregationRunStatus.InProcess in the schema.
        /// </summary>
        InProcess = 2,    
        /// <summary>
        /// There are no comments for AggregationRunStatus.Complete in the schema.
        /// </summary>
        Complete = 4
    }

}
