//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 9/7/2016 8:28:11 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.TelephoneNumber in the schema.
    /// </summary>
    [Table(Name = @"public.telephonenumber")]
    public partial class TelephoneNumber : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private string _EmrIdentifier;

        private PhoneNumber _Number;

        private System.Nullable<System.DateTime> _DateFirstReported;

        private System.Nullable<System.DateTime> _DateLastReported;

        private long _Patientdbid;

        private System.DateTime _UpdateTime;

        private string _LastImportFileDate;
        #pragma warning restore 0649

        private EntityRef<Patient> _Patient;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnEmrIdentifierChanging(string value);
        partial void OnEmrIdentifierChanged();
        partial void OnNumberChanging(PhoneNumber value);
        partial void OnNumberChanged();
        partial void OnDateFirstReportedChanging(System.Nullable<System.DateTime> value);
        partial void OnDateFirstReportedChanged();
        partial void OnDateLastReportedChanging(System.Nullable<System.DateTime> value);
        partial void OnDateLastReportedChanged();
        partial void OnPatientdbidChanging(long value);
        partial void OnPatientdbidChanged();
        partial void OnUpdateTimeChanging(System.DateTime value);
        partial void OnUpdateTimeChanged();
        partial void OnLastImportFileDateChanging(string value);
        partial void OnLastImportFileDateChanged();
        #endregion

        public TelephoneNumber()
        {
            this._Number = new PhoneNumber();
            this._Patient  = default(EntityRef<Patient>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for EmrIdentifier in the schema.
        /// </summary>
        [Column(Name = @"emridentifier", Storage = "_EmrIdentifier", CanBeNull = false, DbType = "varchar NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string EmrIdentifier
        {
            get
            {
                return this._EmrIdentifier;
            }
            set
            {
                if (this._EmrIdentifier != value)
                {
                    this.OnEmrIdentifierChanging(value);
                    this.SendPropertyChanging();
                    this._EmrIdentifier = value;
                    this.SendPropertyChanged("EmrIdentifier");
                    this.OnEmrIdentifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Number in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.ValueTypeProperty()]
        [Devart.Data.Linq.Mapping.Column(Member = "Number", Name = @"number", Storage = "_Number", DbType = "varchar NOT NULL")]
        [Devart.Data.Linq.Mapping.Column(Member = "PhoneType", Name = @"phonetype", Storage = "_PhoneType", DbType = "smallint NOT NULL")]
        public PhoneNumber Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                if (this._Number != value)
                {
                    this.OnNumberChanging(value);
                    this.SendPropertyChanging();
                    this._Number = value;
                    this.SendPropertyChanged("Number");
                    this.OnNumberChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DateFirstReported in the schema.
        /// </summary>
        [Column(Name = @"datefirstreported", Storage = "_DateFirstReported", DbType = "timestamp", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> DateFirstReported
        {
            get
            {
                return this._DateFirstReported;
            }
            set
            {
                if (this._DateFirstReported != value)
                {
                    this.OnDateFirstReportedChanging(value);
                    this.SendPropertyChanging();
                    this._DateFirstReported = value;
                    this.SendPropertyChanged("DateFirstReported");
                    this.OnDateFirstReportedChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DateLastReported in the schema.
        /// </summary>
        [Column(Name = @"datelastreported", Storage = "_DateLastReported", DbType = "timestamp", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> DateLastReported
        {
            get
            {
                return this._DateLastReported;
            }
            set
            {
                if (this._DateLastReported != value)
                {
                    this.OnDateLastReportedChanging(value);
                    this.SendPropertyChanging();
                    this._DateLastReported = value;
                    this.SendPropertyChanged("DateLastReported");
                    this.OnDateLastReportedChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patientdbid in the schema.
        /// </summary>
        [Column(Name = @"patientdbid", Storage = "_Patientdbid", AutoSync = AutoSync.Always, CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Patientdbid
        {
            get
            {
                return this._Patientdbid;
            }
            set
            {
                if (this._Patientdbid != value)
                {
                    if (this._Patient.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnPatientdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Patientdbid = value;
                    this.SendPropertyChanged("Patientdbid");
                    this.OnPatientdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for UpdateTime in the schema.
        /// </summary>
        [Column(Name = @"updatetime", Storage = "_UpdateTime", CanBeNull = false, DbType = "timestamp NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime UpdateTime
        {
            get
            {
                return this._UpdateTime;
            }
            set
            {
                if (this._UpdateTime != value)
                {
                    this.OnUpdateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._UpdateTime = value;
                    this.SendPropertyChanged("UpdateTime");
                    this.OnUpdateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for LastImportFileDate in the schema.
        /// </summary>
        [Column(Name = @"lastimportfiledate", Storage = "_LastImportFileDate", CanBeNull = false, DbType = "varchar NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string LastImportFileDate
        {
            get
            {
                return this._LastImportFileDate;
            }
            set
            {
                if (this._LastImportFileDate != value)
                {
                    this.OnLastImportFileDateChanging(value);
                    this.SendPropertyChanging();
                    this._LastImportFileDate = value;
                    this.SendPropertyChanged("LastImportFileDate");
                    this.OnLastImportFileDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_TelephoneNumber", Storage="_Patient", ThisKey="Patientdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Patient Patient
        {
            get
            {
                return this._Patient.Entity;
            }
            set
            {
                Patient previousValue = this._Patient.Entity;
                if ((previousValue != value) || (this._Patient.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Patient.Entity = null;
                        previousValue.TelephoneNumbers.Remove(this);
                    }
                    this._Patient.Entity = value;
                    if (value != null)
                    {
                        this._Patientdbid = value.dbid;
                        value.TelephoneNumbers.Add(this);
                    }
                    else
                    {
                        this._Patientdbid = default(long);
                    }
                    this.SendPropertyChanged("Patient");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
