//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 5/26/2016 10:47:17 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// All measurements, including labs and vitals
    /// </summary>
    [Table(Name = @"public.measurement")]
    public partial class Measurement : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private string _EmrIdentifier;

        private string _Name;

        private string _Description;

        private string _Comments;

        private CodedEntry _MeasurementCode;

        private System.Nullable<System.DateTimeOffset> _AssessmentDateTime;

        private string _Value;

        private string _Units;

        private string _NormalRangeLow;

        private string _NormalRangeHigh;

        private System.Nullable<bool> _AbnormalFlag;

        private long _Patientdbid;

        private System.Nullable<long> _VisitEncounterdbid;
        #pragma warning restore 0649

        private EntityRef<Patient> _Patient;

        private EntityRef<VisitEncounter> _VisitEncounter;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnEmrIdentifierChanging(string value);
        partial void OnEmrIdentifierChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        partial void OnMeasurementCodeChanging(CodedEntry value);
        partial void OnMeasurementCodeChanged();
        partial void OnAssessmentDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnAssessmentDateTimeChanged();
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        partial void OnUnitsChanging(string value);
        partial void OnUnitsChanged();
        partial void OnNormalRangeLowChanging(string value);
        partial void OnNormalRangeLowChanged();
        partial void OnNormalRangeHighChanging(string value);
        partial void OnNormalRangeHighChanged();
        partial void OnAbnormalFlagChanging(System.Nullable<bool> value);
        partial void OnAbnormalFlagChanged();
        partial void OnPatientdbidChanging(long value);
        partial void OnPatientdbidChanged();
        partial void OnVisitEncounterdbidChanging(System.Nullable<long> value);
        partial void OnVisitEncounterdbidChanged();
        #endregion

        public Measurement()
        {
            this._MeasurementCode = new CodedEntry();
            this._Patient  = default(EntityRef<Patient>);
            this._VisitEncounter  = default(EntityRef<VisitEncounter>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for EmrIdentifier in the schema.
        /// </summary>
        [Column(Name = @"emridentifier", Storage = "_EmrIdentifier", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string EmrIdentifier
        {
            get
            {
                return this._EmrIdentifier;
            }
            set
            {
                if (this._EmrIdentifier != value)
                {
                    this.OnEmrIdentifierChanging(value);
                    this.SendPropertyChanging();
                    this._EmrIdentifier = value;
                    this.SendPropertyChanged("EmrIdentifier");
                    this.OnEmrIdentifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Name = @"name", Storage = "_Name", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging();
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        [Column(Name = @"description", Storage = "_Description", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if (this._Description != value)
                {
                    this.OnDescriptionChanging(value);
                    this.SendPropertyChanging();
                    this._Description = value;
                    this.SendPropertyChanged("Description");
                    this.OnDescriptionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        [Column(Name = @"comments", Storage = "_Comments", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                if (this._Comments != value)
                {
                    this.OnCommentsChanging(value);
                    this.SendPropertyChanging();
                    this._Comments = value;
                    this.SendPropertyChanged("Comments");
                    this.OnCommentsChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MeasurementCode in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.ValueTypeProperty()]
        [Devart.Data.Linq.Mapping.Column(Member = "Code", Name = @"code", Storage = "_Code", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystem", Name = @"codesystem", Storage = "_CodeSystem", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystemVersion", Name = @"codesystemversion", Storage = "_CodeSystemVersion", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeMeaning", Name = @"codemeaning", Storage = "_CodeMeaning", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeModifier", Name = @"codemodifier", Storage = "_CodeModifier", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeModifierDescription", Name = @"codemodifierdescription", Storage = "_CodeModifierDescription", DbType = "varchar")]
        public CodedEntry MeasurementCode
        {
            get
            {
                return this._MeasurementCode;
            }
            set
            {
                if (this._MeasurementCode != value)
                {
                    this.OnMeasurementCodeChanging(value);
                    this.SendPropertyChanging();
                    this._MeasurementCode = value;
                    this.SendPropertyChanged("MeasurementCode");
                    this.OnMeasurementCodeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for AssessmentDateTime in the schema.
        /// </summary>
        [Column(Name = @"assessmentdatetime", Storage = "_AssessmentDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> AssessmentDateTime
        {
            get
            {
                return this._AssessmentDateTime;
            }
            set
            {
                if (this._AssessmentDateTime != value)
                {
                    this.OnAssessmentDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._AssessmentDateTime = value;
                    this.SendPropertyChanged("AssessmentDateTime");
                    this.OnAssessmentDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Value in the schema.
        /// </summary>
        [Column(Name = @"value", Storage = "_Value", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                if (this._Value != value)
                {
                    this.OnValueChanging(value);
                    this.SendPropertyChanging();
                    this._Value = value;
                    this.SendPropertyChanged("Value");
                    this.OnValueChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Units in the schema.
        /// </summary>
        [Column(Name = @"units", Storage = "_Units", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Units
        {
            get
            {
                return this._Units;
            }
            set
            {
                if (this._Units != value)
                {
                    this.OnUnitsChanging(value);
                    this.SendPropertyChanging();
                    this._Units = value;
                    this.SendPropertyChanged("Units");
                    this.OnUnitsChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NormalRangeLow in the schema.
        /// </summary>
        [Column(Name = @"normalrangelow", Storage = "_NormalRangeLow", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string NormalRangeLow
        {
            get
            {
                return this._NormalRangeLow;
            }
            set
            {
                if (this._NormalRangeLow != value)
                {
                    this.OnNormalRangeLowChanging(value);
                    this.SendPropertyChanging();
                    this._NormalRangeLow = value;
                    this.SendPropertyChanged("NormalRangeLow");
                    this.OnNormalRangeLowChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NormalRangeHigh in the schema.
        /// </summary>
        [Column(Name = @"normalrangehigh", Storage = "_NormalRangeHigh", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string NormalRangeHigh
        {
            get
            {
                return this._NormalRangeHigh;
            }
            set
            {
                if (this._NormalRangeHigh != value)
                {
                    this.OnNormalRangeHighChanging(value);
                    this.SendPropertyChanging();
                    this._NormalRangeHigh = value;
                    this.SendPropertyChanged("NormalRangeHigh");
                    this.OnNormalRangeHighChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for AbnormalFlag in the schema.
        /// </summary>
        [Column(Name = @"abnormalflag", Storage = "_AbnormalFlag", DbType = "boolean", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<bool> AbnormalFlag
        {
            get
            {
                return this._AbnormalFlag;
            }
            set
            {
                if (this._AbnormalFlag != value)
                {
                    this.OnAbnormalFlagChanging(value);
                    this.SendPropertyChanging();
                    this._AbnormalFlag = value;
                    this.SendPropertyChanged("AbnormalFlag");
                    this.OnAbnormalFlagChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patientdbid in the schema.
        /// </summary>
        [Column(Name = @"patientdbid", Storage = "_Patientdbid", AutoSync = AutoSync.Always, CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Patientdbid
        {
            get
            {
                return this._Patientdbid;
            }
            set
            {
                if (this._Patientdbid != value)
                {
                    if (this._Patient.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnPatientdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Patientdbid = value;
                    this.SendPropertyChanged("Patientdbid");
                    this.OnPatientdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounterdbid in the schema.
        /// </summary>
        [Column(Name = @"visitencounterdbid", Storage = "_VisitEncounterdbid", AutoSync = AutoSync.Always, DbType = "int8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> VisitEncounterdbid
        {
            get
            {
                return this._VisitEncounterdbid;
            }
            set
            {
                if (this._VisitEncounterdbid != value)
                {
                    if (this._VisitEncounter.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnVisitEncounterdbidChanging(value);
                    this.SendPropertyChanging();
                    this._VisitEncounterdbid = value;
                    this.SendPropertyChanged("VisitEncounterdbid");
                    this.OnVisitEncounterdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Measurement", Storage="_Patient", ThisKey="Patientdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Patient Patient
        {
            get
            {
                return this._Patient.Entity;
            }
            set
            {
                Patient previousValue = this._Patient.Entity;
                if ((previousValue != value) || (this._Patient.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Patient.Entity = null;
                        previousValue.Measurements.Remove(this);
                    }
                    this._Patient.Entity = value;
                    if (value != null)
                    {
                        this._Patientdbid = value.dbid;
                        value.Measurements.Add(this);
                    }
                    else
                    {
                        this._Patientdbid = default(long);
                    }
                    this.SendPropertyChanged("Patient");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounter in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Measurement", Storage="_VisitEncounter", ThisKey="VisitEncounterdbid", OtherKey="dbid", IsForeignKey=true)]
        public VisitEncounter VisitEncounter
        {
            get
            {
                return this._VisitEncounter.Entity;
            }
            set
            {
                VisitEncounter previousValue = this._VisitEncounter.Entity;
                if ((previousValue != value) || (this._VisitEncounter.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._VisitEncounter.Entity = null;
                        previousValue.Results.Remove(this);
                    }
                    this._VisitEncounter.Entity = value;
                    if (value != null)
                    {
                        this._VisitEncounterdbid = value.dbid;
                        value.Results.Add(this);
                    }
                    else
                    {
                        this._VisitEncounterdbid = default(System.Nullable<long>);
                    }
                    this.SendPropertyChanged("VisitEncounter");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
