//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 6/21/2016 10:54:10 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for AddressType in the schema.
    /// </summary>
    public enum AddressType : short
    {
    
        /// <summary>
        /// There are no comments for AddressType.Unspecified in the schema.
        /// </summary>
        Unspecified,    
        /// <summary>
        /// There are no comments for AddressType.Home in the schema.
        /// </summary>
        Home,    
        /// <summary>
        /// There are no comments for AddressType.Business in the schema.
        /// </summary>
        Business,    
        /// <summary>
        /// There are no comments for AddressType.Mailing in the schema.
        /// </summary>
        Mailing,    
        /// <summary>
        /// There are no comments for AddressType.ePrescribing in the schema.
        /// </summary>
        ePrescribing
    }

}
