//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 6/28/2016 3:21:46 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.Patient in the schema.
    /// </summary>
    [Table(Name = @"public.patient")]
    public partial class Patient : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private string _EmrIdentifier;

        private string _NameLast;

        private string _NameFirst;

        private string _NameMiddle;

        private System.Nullable<System.DateTime> _BirthDate;

        private System.Nullable<Gender> _Gender;

        private System.Nullable<System.DateTime> _DeathDate;

        private string _Race;

        private string _Ethnicity;

        private System.Nullable<MaritalStatus> _MaritalStatus;

        private string _LatestImportFileDate;

        private System.DateTime _UpdateTime;
        #pragma warning restore 0649

        private EntitySet<PatientIdentifier> _PatientIdentifiers;

        private EntitySet<PhysicalAddress> _PhysicalAddresses;

        private EntitySet<TelephoneNumber> _TelephoneNumbers;

        private EntitySet<VisitEncounter> _VisitEncounters;

        private EntitySet<Measurement> _Measurements;

        private EntitySet<Medication> _Medications;

        private EntitySet<Immunization> _Immunizations;

        private EntitySet<InsuranceCoverage> _InsuranceCoverages;

        private EntitySet<Diagnosis> _Diagnoses;

        private EntitySet<Problem> _Problems;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnEmrIdentifierChanging(string value);
        partial void OnEmrIdentifierChanged();
        partial void OnNameLastChanging(string value);
        partial void OnNameLastChanged();
        partial void OnNameFirstChanging(string value);
        partial void OnNameFirstChanged();
        partial void OnNameMiddleChanging(string value);
        partial void OnNameMiddleChanged();
        partial void OnBirthDateChanging(System.Nullable<System.DateTime> value);
        partial void OnBirthDateChanged();
        partial void OnGenderChanging(System.Nullable<Gender> value);
        partial void OnGenderChanged();
        partial void OnDeathDateChanging(System.Nullable<System.DateTime> value);
        partial void OnDeathDateChanged();
        partial void OnRaceChanging(string value);
        partial void OnRaceChanged();
        partial void OnEthnicityChanging(string value);
        partial void OnEthnicityChanged();
        partial void OnMaritalStatusChanging(System.Nullable<MaritalStatus> value);
        partial void OnMaritalStatusChanged();
        partial void OnLatestImportFileDateChanging(string value);
        partial void OnLatestImportFileDateChanged();
        partial void OnUpdateTimeChanging(System.DateTime value);
        partial void OnUpdateTimeChanged();
        #endregion

        public Patient()
        {
            this._PatientIdentifiers = new EntitySet<PatientIdentifier>(new Action<PatientIdentifier>(this.attach_PatientIdentifiers), new Action<PatientIdentifier>(this.detach_PatientIdentifiers));
            this._PhysicalAddresses = new EntitySet<PhysicalAddress>(new Action<PhysicalAddress>(this.attach_PhysicalAddresses), new Action<PhysicalAddress>(this.detach_PhysicalAddresses));
            this._TelephoneNumbers = new EntitySet<TelephoneNumber>(new Action<TelephoneNumber>(this.attach_TelephoneNumbers), new Action<TelephoneNumber>(this.detach_TelephoneNumbers));
            this._VisitEncounters = new EntitySet<VisitEncounter>(new Action<VisitEncounter>(this.attach_VisitEncounters), new Action<VisitEncounter>(this.detach_VisitEncounters));
            this._Measurements = new EntitySet<Measurement>(new Action<Measurement>(this.attach_Measurements), new Action<Measurement>(this.detach_Measurements));
            this._Medications = new EntitySet<Medication>(new Action<Medication>(this.attach_Medications), new Action<Medication>(this.detach_Medications));
            this._Immunizations = new EntitySet<Immunization>(new Action<Immunization>(this.attach_Immunizations), new Action<Immunization>(this.detach_Immunizations));
            this._InsuranceCoverages = new EntitySet<InsuranceCoverage>(new Action<InsuranceCoverage>(this.attach_InsuranceCoverages), new Action<InsuranceCoverage>(this.detach_InsuranceCoverages));
            this._Diagnoses = new EntitySet<Diagnosis>(new Action<Diagnosis>(this.attach_Diagnoses), new Action<Diagnosis>(this.detach_Diagnoses));
            this._Problems = new EntitySet<Problem>(new Action<Problem>(this.attach_Problems), new Action<Problem>(this.detach_Problems));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for EmrIdentifier in the schema.
        /// </summary>
        [Column(Name = @"emridentifier", Storage = "_EmrIdentifier", CanBeNull = false, DbType = "varchar NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string EmrIdentifier
        {
            get
            {
                return this._EmrIdentifier;
            }
            set
            {
                if (this._EmrIdentifier != value)
                {
                    this.OnEmrIdentifierChanging(value);
                    this.SendPropertyChanging();
                    this._EmrIdentifier = value;
                    this.SendPropertyChanged("EmrIdentifier");
                    this.OnEmrIdentifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NameLast in the schema.
        /// </summary>
        [Column(Name = @"namelast", Storage = "_NameLast", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string NameLast
        {
            get
            {
                return this._NameLast;
            }
            set
            {
                if (this._NameLast != value)
                {
                    this.OnNameLastChanging(value);
                    this.SendPropertyChanging();
                    this._NameLast = value;
                    this.SendPropertyChanged("NameLast");
                    this.OnNameLastChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NameFirst in the schema.
        /// </summary>
        [Column(Name = @"namefirst", Storage = "_NameFirst", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string NameFirst
        {
            get
            {
                return this._NameFirst;
            }
            set
            {
                if (this._NameFirst != value)
                {
                    this.OnNameFirstChanging(value);
                    this.SendPropertyChanging();
                    this._NameFirst = value;
                    this.SendPropertyChanged("NameFirst");
                    this.OnNameFirstChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NameMiddle in the schema.
        /// </summary>
        [Column(Name = @"namemiddle", Storage = "_NameMiddle", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string NameMiddle
        {
            get
            {
                return this._NameMiddle;
            }
            set
            {
                if (this._NameMiddle != value)
                {
                    this.OnNameMiddleChanging(value);
                    this.SendPropertyChanging();
                    this._NameMiddle = value;
                    this.SendPropertyChanged("NameMiddle");
                    this.OnNameMiddleChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BirthDate in the schema.
        /// </summary>
        [Column(Name = @"birthdate", Storage = "_BirthDate", DbType = "timestamp", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this._BirthDate;
            }
            set
            {
                if (this._BirthDate != value)
                {
                    this.OnBirthDateChanging(value);
                    this.SendPropertyChanging();
                    this._BirthDate = value;
                    this.SendPropertyChanged("BirthDate");
                    this.OnBirthDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Gender in the schema.
        /// </summary>
        [Column(Name = @"gender", Storage = "_Gender", DbType = "INT2", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<Gender> Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                if (this._Gender != value)
                {
                    this.OnGenderChanging(value);
                    this.SendPropertyChanging();
                    this._Gender = value;
                    this.SendPropertyChanged("Gender");
                    this.OnGenderChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DeathDate in the schema.
        /// </summary>
        [Column(Name = @"deathdate", Storage = "_DeathDate", DbType = "timestamp", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> DeathDate
        {
            get
            {
                return this._DeathDate;
            }
            set
            {
                if (this._DeathDate != value)
                {
                    this.OnDeathDateChanging(value);
                    this.SendPropertyChanging();
                    this._DeathDate = value;
                    this.SendPropertyChanged("DeathDate");
                    this.OnDeathDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Race in the schema.
        /// </summary>
        [Column(Name = @"race", Storage = "_Race", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Race
        {
            get
            {
                return this._Race;
            }
            set
            {
                if (this._Race != value)
                {
                    this.OnRaceChanging(value);
                    this.SendPropertyChanging();
                    this._Race = value;
                    this.SendPropertyChanged("Race");
                    this.OnRaceChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Ethnicity in the schema.
        /// </summary>
        [Column(Name = @"ethnicity", Storage = "_Ethnicity", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Ethnicity
        {
            get
            {
                return this._Ethnicity;
            }
            set
            {
                if (this._Ethnicity != value)
                {
                    this.OnEthnicityChanging(value);
                    this.SendPropertyChanging();
                    this._Ethnicity = value;
                    this.SendPropertyChanged("Ethnicity");
                    this.OnEthnicityChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MaritalStatus in the schema.
        /// </summary>
        [Column(Name = @"maritalstatus", Storage = "_MaritalStatus", DbType = "INT2", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<MaritalStatus> MaritalStatus
        {
            get
            {
                return this._MaritalStatus;
            }
            set
            {
                if (this._MaritalStatus != value)
                {
                    this.OnMaritalStatusChanging(value);
                    this.SendPropertyChanging();
                    this._MaritalStatus = value;
                    this.SendPropertyChanged("MaritalStatus");
                    this.OnMaritalStatusChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for LatestImportFileDate in the schema.
        /// </summary>
        [Column(Name = @"latestimportfiledate", Storage = "_LatestImportFileDate", CanBeNull = false, DbType = "varchar(8) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string LatestImportFileDate
        {
            get
            {
                return this._LatestImportFileDate;
            }
            set
            {
                if (this._LatestImportFileDate != value)
                {
                    this.OnLatestImportFileDateChanging(value);
                    this.SendPropertyChanging();
                    this._LatestImportFileDate = value;
                    this.SendPropertyChanged("LatestImportFileDate");
                    this.OnLatestImportFileDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for UpdateTime in the schema.
        /// </summary>
        [Column(Name = @"updatetime", Storage = "_UpdateTime", CanBeNull = false, DbType = "timestamp NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime UpdateTime
        {
            get
            {
                return this._UpdateTime;
            }
            set
            {
                if (this._UpdateTime != value)
                {
                    this.OnUpdateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._UpdateTime = value;
                    this.SendPropertyChanged("UpdateTime");
                    this.OnUpdateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PatientIdentifiers in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_PatientIdentifier", Storage="_PatientIdentifiers", ThisKey="dbid", OtherKey="Patientdbid", DeleteRule="NO ACTION")]
        public EntitySet<PatientIdentifier> PatientIdentifiers
        {
            get
            {
                return this._PatientIdentifiers;
            }
            set
            {
                this._PatientIdentifiers.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for PhysicalAddresses in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_PatientAddress", Storage="_PhysicalAddresses", ThisKey="dbid", OtherKey="Patientdbid")]
        public EntitySet<PhysicalAddress> PhysicalAddresses
        {
            get
            {
                return this._PhysicalAddresses;
            }
            set
            {
                this._PhysicalAddresses.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for TelephoneNumbers in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_TelephoneNumber", Storage="_TelephoneNumbers", ThisKey="dbid", OtherKey="Patientdbid")]
        public EntitySet<TelephoneNumber> TelephoneNumbers
        {
            get
            {
                return this._TelephoneNumbers;
            }
            set
            {
                this._TelephoneNumbers.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounters in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_VisitEncounter", Storage="_VisitEncounters", ThisKey="dbid", OtherKey="Patientdbid")]
        public EntitySet<VisitEncounter> VisitEncounters
        {
            get
            {
                return this._VisitEncounters;
            }
            set
            {
                this._VisitEncounters.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Measurements in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Measurement", Storage="_Measurements", ThisKey="dbid", OtherKey="Patientdbid")]
        public EntitySet<Measurement> Measurements
        {
            get
            {
                return this._Measurements;
            }
            set
            {
                this._Measurements.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Medications in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Medication", Storage="_Medications", ThisKey="dbid", OtherKey="Patientdbid")]
        public EntitySet<Medication> Medications
        {
            get
            {
                return this._Medications;
            }
            set
            {
                this._Medications.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Immunizations in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Immunization", Storage="_Immunizations", ThisKey="dbid", OtherKey="Patientdbid")]
        public EntitySet<Immunization> Immunizations
        {
            get
            {
                return this._Immunizations;
            }
            set
            {
                this._Immunizations.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for InsuranceCoverages in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_InsuranceCoverage", Storage="_InsuranceCoverages", ThisKey="dbid", OtherKey="Patientdbid")]
        public EntitySet<InsuranceCoverage> InsuranceCoverages
        {
            get
            {
                return this._InsuranceCoverages;
            }
            set
            {
                this._InsuranceCoverages.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Diagnoses in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Diagnosis", Storage="_Diagnoses", ThisKey="dbid", OtherKey="Patientdbid")]
        public EntitySet<Diagnosis> Diagnoses
        {
            get
            {
                return this._Diagnoses;
            }
            set
            {
                this._Diagnoses.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Problems in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Problem", Storage="_Problems", ThisKey="dbid", OtherKey="Patientdbid")]
        public EntitySet<Problem> Problems
        {
            get
            {
                return this._Problems;
            }
            set
            {
                this._Problems.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_PatientIdentifiers(PatientIdentifier entity)
        {
            this.SendPropertyChanging("PatientIdentifiers");
            entity.Patient = this;
        }
    
        private void detach_PatientIdentifiers(PatientIdentifier entity)
        {
            this.SendPropertyChanging("PatientIdentifiers");
            entity.Patient = null;
        }

        private void attach_PhysicalAddresses(PhysicalAddress entity)
        {
            this.SendPropertyChanging("PhysicalAddresses");
            entity.patient = this;
        }
    
        private void detach_PhysicalAddresses(PhysicalAddress entity)
        {
            this.SendPropertyChanging("PhysicalAddresses");
            entity.patient = null;
        }

        private void attach_TelephoneNumbers(TelephoneNumber entity)
        {
            this.SendPropertyChanging("TelephoneNumbers");
            entity.Patient = this;
        }
    
        private void detach_TelephoneNumbers(TelephoneNumber entity)
        {
            this.SendPropertyChanging("TelephoneNumbers");
            entity.Patient = null;
        }

        private void attach_VisitEncounters(VisitEncounter entity)
        {
            this.SendPropertyChanging("VisitEncounters");
            entity.Patient = this;
        }
    
        private void detach_VisitEncounters(VisitEncounter entity)
        {
            this.SendPropertyChanging("VisitEncounters");
            entity.Patient = null;
        }

        private void attach_Measurements(Measurement entity)
        {
            this.SendPropertyChanging("Measurements");
            entity.Patient = this;
        }
    
        private void detach_Measurements(Measurement entity)
        {
            this.SendPropertyChanging("Measurements");
            entity.Patient = null;
        }

        private void attach_Medications(Medication entity)
        {
            this.SendPropertyChanging("Medications");
            entity.Patient = this;
        }
    
        private void detach_Medications(Medication entity)
        {
            this.SendPropertyChanging("Medications");
            entity.Patient = null;
        }

        private void attach_Immunizations(Immunization entity)
        {
            this.SendPropertyChanging("Immunizations");
            entity.Patient = this;
        }
    
        private void detach_Immunizations(Immunization entity)
        {
            this.SendPropertyChanging("Immunizations");
            entity.Patient = null;
        }

        private void attach_InsuranceCoverages(InsuranceCoverage entity)
        {
            this.SendPropertyChanging("InsuranceCoverages");
            entity.Patient = this;
        }
    
        private void detach_InsuranceCoverages(InsuranceCoverage entity)
        {
            this.SendPropertyChanging("InsuranceCoverages");
            entity.Patient = null;
        }

        private void attach_Diagnoses(Diagnosis entity)
        {
            this.SendPropertyChanging("Diagnoses");
            entity.Patient = this;
        }
    
        private void detach_Diagnoses(Diagnosis entity)
        {
            this.SendPropertyChanging("Diagnoses");
            entity.Patient = null;
        }

        private void attach_Problems(Problem entity)
        {
            this.SendPropertyChanging("Problems");
            entity.Patient = this;
        }
    
        private void detach_Problems(Problem entity)
        {
            this.SendPropertyChanging("Problems");
            entity.Patient = null;
        }
    }

}
