//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 8/25/2016 3:56:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for Gender in the schema.
    /// </summary>
    public enum Gender : short
    {
    
        /// <summary>
        /// There are no comments for Gender.Male in the schema.
        /// </summary>
        Male,    
        /// <summary>
        /// There are no comments for Gender.Female in the schema.
        /// </summary>
        Female,    
        /// <summary>
        /// There are no comments for Gender.Unspecified in the schema.
        /// </summary>
        Unspecified,    
        /// <summary>
        /// There are no comments for Gender.Unknown in the schema.
        /// </summary>
        Unknown
    }

}
