//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 3/7/2016 3:18:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.PhysicalAddress in the schema.
    /// </summary>
    [Table(Name = @"public.physicaladdress")]
    public partial class PhysicalAddress : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private Address _Address;

        private long _Patientdbid;

        private System.Nullable<System.DateTime> _DateValid;

        private long _TelephoneNumberdbid;

        private long _TelephoneNumberdbid1;
        #pragma warning restore 0649

        private EntityRef<Patient> _patient;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnAddressChanging(Address value);
        partial void OnAddressChanged();
        partial void OnPatientdbidChanging(long value);
        partial void OnPatientdbidChanged();
        partial void OnDateValidChanging(System.Nullable<System.DateTime> value);
        partial void OnDateValidChanged();
        partial void OnTelephoneNumberdbidChanging(long value);
        partial void OnTelephoneNumberdbidChanged();
        partial void OnTelephoneNumberdbid1Changing(long value);
        partial void OnTelephoneNumberdbid1Changed();
        #endregion

        public PhysicalAddress()
        {
            this._Address = new Address();
            this._patient  = default(EntityRef<Patient>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.ValueTypeProperty()]
        [Devart.Data.Linq.Mapping.Column(Member = "City", Name = @"city", Storage = "_City", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "State", Name = @"""state""", Storage = "_State", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "PostalCode", Name = @"postalcode", Storage = "_PostalCode", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "Country", Name = @"country", Storage = "_Country", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "Line1", Name = @"line1", Storage = "_Line1", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "Line2", Name = @"line2", Storage = "_Line2", DbType = "varchar")]
        public Address Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                if (this._Address != value)
                {
                    this.OnAddressChanging(value);
                    this.SendPropertyChanging();
                    this._Address = value;
                    this.SendPropertyChanged("Address");
                    this.OnAddressChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patientdbid in the schema.
        /// </summary>
        [Column(Name = @"patientdbid", Storage = "_Patientdbid", CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Patientdbid
        {
            get
            {
                return this._Patientdbid;
            }
            set
            {
                if (this._Patientdbid != value)
                {
                    if (this._patient.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnPatientdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Patientdbid = value;
                    this.SendPropertyChanged("Patientdbid");
                    this.OnPatientdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DateValid in the schema.
        /// </summary>
        [Column(Name = @"datevalid", Storage = "_DateValid", DbType = "timestamp", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> DateValid
        {
            get
            {
                return this._DateValid;
            }
            set
            {
                if (this._DateValid != value)
                {
                    this.OnDateValidChanging(value);
                    this.SendPropertyChanging();
                    this._DateValid = value;
                    this.SendPropertyChanged("DateValid");
                    this.OnDateValidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TelephoneNumberdbid in the schema.
        /// </summary>
        [Column(Name = @"""TelephoneNumber_PhysicalAddress""", Storage = "_TelephoneNumberdbid", CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long TelephoneNumberdbid
        {
            get
            {
                return this._TelephoneNumberdbid;
            }
            set
            {
                if (this._TelephoneNumberdbid != value)
                {
                    this.OnTelephoneNumberdbidChanging(value);
                    this.SendPropertyChanging();
                    this._TelephoneNumberdbid = value;
                    this.SendPropertyChanged("TelephoneNumberdbid");
                    this.OnTelephoneNumberdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TelephoneNumberdbid1 in the schema.
        /// </summary>
        [Column(Name = @"""PhysicalAddress_TelephoneNumber""", Storage = "_TelephoneNumberdbid1", CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long TelephoneNumberdbid1
        {
            get
            {
                return this._TelephoneNumberdbid1;
            }
            set
            {
                if (this._TelephoneNumberdbid1 != value)
                {
                    this.OnTelephoneNumberdbid1Changing(value);
                    this.SendPropertyChanging();
                    this._TelephoneNumberdbid1 = value;
                    this.SendPropertyChanged("TelephoneNumberdbid1");
                    this.OnTelephoneNumberdbid1Changed();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for patient in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_PatientAddress", Storage="_patient", ThisKey="Patientdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Patient patient
        {
            get
            {
                return this._patient.Entity;
            }
            set
            {
                Patient previousValue = this._patient.Entity;
                if ((previousValue != value) || (this._patient.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._patient.Entity = null;
                        previousValue.PhysicalAddresses.Remove(this);
                    }
                    this._patient.Entity = value;
                    if (value != null)
                    {
                        this._Patientdbid = value.dbid;
                        value.PhysicalAddresses.Add(this);
                    }
                    else
                    {
                        this._Patientdbid = default(long);
                    }
                    this.SendPropertyChanged("patient");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
