//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 3/7/2016 3:18:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.DataFeed in the schema.
    /// </summary>
    [Table(Name = @"public.datafeed")]
    public partial class DataFeed : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private string _FeedName;

        private long _Organizationdbid;
        #pragma warning restore 0649

        private EntityRef<Organization> _Organization;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnFeedNameChanging(string value);
        partial void OnFeedNameChanged();
        partial void OnOrganizationdbidChanging(long value);
        partial void OnOrganizationdbidChanged();
        #endregion

        public DataFeed()
        {
            this._Organization  = default(EntityRef<Organization>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for FeedName in the schema.
        /// </summary>
        [Column(Name = @"feedname", Storage = "_FeedName", CanBeNull = false, DbType = "varchar NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string FeedName
        {
            get
            {
                return this._FeedName;
            }
            set
            {
                if (this._FeedName != value)
                {
                    this.OnFeedNameChanging(value);
                    this.SendPropertyChanging();
                    this._FeedName = value;
                    this.SendPropertyChanged("FeedName");
                    this.OnFeedNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Organizationdbid in the schema.
        /// </summary>
        [Column(Name = @"organizationdbid", Storage = "_Organizationdbid", CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Organizationdbid
        {
            get
            {
                return this._Organizationdbid;
            }
            set
            {
                if (this._Organizationdbid != value)
                {
                    if (this._Organization.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnOrganizationdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Organizationdbid = value;
                    this.SendPropertyChanged("Organizationdbid");
                    this.OnOrganizationdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Organization in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Organization_DataFeed", Storage="_Organization", ThisKey="Organizationdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Organization Organization
        {
            get
            {
                return this._Organization.Entity;
            }
            set
            {
                Organization previousValue = this._Organization.Entity;
                if ((previousValue != value) || (this._Organization.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Organization.Entity = null;
                        previousValue.DataFeeds.Remove(this);
                    }
                    this._Organization.Entity = value;
                    if (value != null)
                    {
                        this._Organizationdbid = value.dbid;
                        value.DataFeeds.Add(this);
                    }
                    else
                    {
                        this._Organizationdbid = default(long);
                    }
                    this.SendPropertyChanged("Organization");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
