//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 6/3/2016 11:14:21 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.VisitEncounter in the schema.
    /// </summary>
    [Table(Name = @"public.visitencounter")]
    public partial class VisitEncounter : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private string _EmrIdentifier;

        private System.Nullable<System.DateTime> _BeginDateTime;

        private System.Nullable<System.DateTime> _EndDateTime;

        private string _Status;

        private System.Nullable<System.DateTime> _StatusDateTime;

        private long _Organizationdbid;

        private long _Patientdbid;
        #pragma warning restore 0649

        private EntityRef<Patient> _Patient;

        private EntityRef<Organization> _Organization;

        private EntitySet<Charge> _Charges;

        private EntitySet<Measurement> _Results;

        private EntitySet<Medication> _Medications;

        private EntitySet<Immunization> _Immunizations;

        private EntitySet<Diagnosis> _Diagnoses;

        private EntitySet<Problem> _Problems;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnEmrIdentifierChanging(string value);
        partial void OnEmrIdentifierChanged();
        partial void OnBeginDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnBeginDateTimeChanged();
        partial void OnEndDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnEndDateTimeChanged();
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        partial void OnStatusDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnStatusDateTimeChanged();
        partial void OnOrganizationdbidChanging(long value);
        partial void OnOrganizationdbidChanged();
        partial void OnPatientdbidChanging(long value);
        partial void OnPatientdbidChanged();
        #endregion

        public VisitEncounter()
        {
            this._Patient  = default(EntityRef<Patient>);
            this._Organization  = default(EntityRef<Organization>);
            this._Charges = new EntitySet<Charge>(new Action<Charge>(this.attach_Charges), new Action<Charge>(this.detach_Charges));
            this._Results = new EntitySet<Measurement>(new Action<Measurement>(this.attach_Results), new Action<Measurement>(this.detach_Results));
            this._Medications = new EntitySet<Medication>(new Action<Medication>(this.attach_Medications), new Action<Medication>(this.detach_Medications));
            this._Immunizations = new EntitySet<Immunization>(new Action<Immunization>(this.attach_Immunizations), new Action<Immunization>(this.detach_Immunizations));
            this._Diagnoses = new EntitySet<Diagnosis>(new Action<Diagnosis>(this.attach_Diagnoses), new Action<Diagnosis>(this.detach_Diagnoses));
            this._Problems = new EntitySet<Problem>(new Action<Problem>(this.attach_Problems), new Action<Problem>(this.detach_Problems));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for EmrIdentifier in the schema.
        /// </summary>
        [Column(Name = @"emridentifier", Storage = "_EmrIdentifier", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string EmrIdentifier
        {
            get
            {
                return this._EmrIdentifier;
            }
            set
            {
                if (this._EmrIdentifier != value)
                {
                    this.OnEmrIdentifierChanging(value);
                    this.SendPropertyChanging();
                    this._EmrIdentifier = value;
                    this.SendPropertyChanged("EmrIdentifier");
                    this.OnEmrIdentifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BeginDateTime in the schema.
        /// </summary>
        [Column(Name = @"begindatetime", Storage = "_BeginDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> BeginDateTime
        {
            get
            {
                return this._BeginDateTime;
            }
            set
            {
                if (this._BeginDateTime != value)
                {
                    this.OnBeginDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BeginDateTime = value;
                    this.SendPropertyChanged("BeginDateTime");
                    this.OnBeginDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EndDateTime in the schema.
        /// </summary>
        [Column(Name = @"enddatetime", Storage = "_EndDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> EndDateTime
        {
            get
            {
                return this._EndDateTime;
            }
            set
            {
                if (this._EndDateTime != value)
                {
                    this.OnEndDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._EndDateTime = value;
                    this.SendPropertyChanged("EndDateTime");
                    this.OnEndDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        [Column(Name = @"status", Storage = "_Status", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                if (this._Status != value)
                {
                    this.OnStatusChanging(value);
                    this.SendPropertyChanging();
                    this._Status = value;
                    this.SendPropertyChanged("Status");
                    this.OnStatusChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for StatusDateTime in the schema.
        /// </summary>
        [Column(Name = @"statusdatetime", Storage = "_StatusDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> StatusDateTime
        {
            get
            {
                return this._StatusDateTime;
            }
            set
            {
                if (this._StatusDateTime != value)
                {
                    this.OnStatusDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._StatusDateTime = value;
                    this.SendPropertyChanged("StatusDateTime");
                    this.OnStatusDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Organizationdbid in the schema.
        /// </summary>
        [Column(Name = @"organizationdbid", Storage = "_Organizationdbid", AutoSync = AutoSync.Always, CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Organizationdbid
        {
            get
            {
                return this._Organizationdbid;
            }
            set
            {
                if (this._Organizationdbid != value)
                {
                    if (this._Organization.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnOrganizationdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Organizationdbid = value;
                    this.SendPropertyChanged("Organizationdbid");
                    this.OnOrganizationdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patientdbid in the schema.
        /// </summary>
        [Column(Name = @"patientdbid", Storage = "_Patientdbid", AutoSync = AutoSync.Always, CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Patientdbid
        {
            get
            {
                return this._Patientdbid;
            }
            set
            {
                if (this._Patientdbid != value)
                {
                    if (this._Patient.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnPatientdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Patientdbid = value;
                    this.SendPropertyChanged("Patientdbid");
                    this.OnPatientdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_VisitEncounter", Storage="_Patient", ThisKey="Patientdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Patient Patient
        {
            get
            {
                return this._Patient.Entity;
            }
            set
            {
                Patient previousValue = this._Patient.Entity;
                if ((previousValue != value) || (this._Patient.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Patient.Entity = null;
                        previousValue.VisitEncounters.Remove(this);
                    }
                    this._Patient.Entity = value;
                    if (value != null)
                    {
                        this._Patientdbid = value.dbid;
                        value.VisitEncounters.Add(this);
                    }
                    else
                    {
                        this._Patientdbid = default(long);
                    }
                    this.SendPropertyChanged("Patient");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Organization in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Organization_VisitEncounter", Storage="_Organization", ThisKey="Organizationdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Organization Organization
        {
            get
            {
                return this._Organization.Entity;
            }
            set
            {
                Organization previousValue = this._Organization.Entity;
                if ((previousValue != value) || (this._Organization.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Organization.Entity = null;
                    }
                    this._Organization.Entity = value;
                    if (value != null)
                    {
                        this._Organizationdbid = value.dbid;
                    }
                    else
                    {
                        this._Organizationdbid = default(long);
                    }
                    this.SendPropertyChanged("Organization");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Charges in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Charge", Storage="_Charges", ThisKey="dbid", OtherKey="VisitEncounterdbid")]
        public EntitySet<Charge> Charges
        {
            get
            {
                return this._Charges;
            }
            set
            {
                this._Charges.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Results in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Measurement", Storage="_Results", ThisKey="dbid", OtherKey="VisitEncounterdbid")]
        public EntitySet<Measurement> Results
        {
            get
            {
                return this._Results;
            }
            set
            {
                this._Results.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Medications in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Medication", Storage="_Medications", ThisKey="dbid", OtherKey="VisitEncounterdbid")]
        public EntitySet<Medication> Medications
        {
            get
            {
                return this._Medications;
            }
            set
            {
                this._Medications.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Immunizations in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Immunization", Storage="_Immunizations", ThisKey="dbid", OtherKey="VisitEncounterdbid")]
        public EntitySet<Immunization> Immunizations
        {
            get
            {
                return this._Immunizations;
            }
            set
            {
                this._Immunizations.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Diagnoses in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Diagnosis", Storage="_Diagnoses", ThisKey="dbid", OtherKey="VisitEncounterdbid")]
        public EntitySet<Diagnosis> Diagnoses
        {
            get
            {
                return this._Diagnoses;
            }
            set
            {
                this._Diagnoses.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Problems in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Problem", Storage="_Problems", ThisKey="dbid", OtherKey="VisitEncounterdbid")]
        public EntitySet<Problem> Problems
        {
            get
            {
                return this._Problems;
            }
            set
            {
                this._Problems.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Charges(Charge entity)
        {
            this.SendPropertyChanging("Charges");
            entity.VisitEncounter = this;
        }
    
        private void detach_Charges(Charge entity)
        {
            this.SendPropertyChanging("Charges");
            entity.VisitEncounter = null;
        }

        private void attach_Results(Measurement entity)
        {
            this.SendPropertyChanging("Results");
            entity.VisitEncounter = this;
        }
    
        private void detach_Results(Measurement entity)
        {
            this.SendPropertyChanging("Results");
            entity.VisitEncounter = null;
        }

        private void attach_Medications(Medication entity)
        {
            this.SendPropertyChanging("Medications");
            entity.VisitEncounter = this;
        }
    
        private void detach_Medications(Medication entity)
        {
            this.SendPropertyChanging("Medications");
            entity.VisitEncounter = null;
        }

        private void attach_Immunizations(Immunization entity)
        {
            this.SendPropertyChanging("Immunizations");
            entity.VisitEncounter = this;
        }
    
        private void detach_Immunizations(Immunization entity)
        {
            this.SendPropertyChanging("Immunizations");
            entity.VisitEncounter = null;
        }

        private void attach_Diagnoses(Diagnosis entity)
        {
            this.SendPropertyChanging("Diagnoses");
            entity.VisitEncounter = this;
        }
    
        private void detach_Diagnoses(Diagnosis entity)
        {
            this.SendPropertyChanging("Diagnoses");
            entity.VisitEncounter = null;
        }

        private void attach_Problems(Problem entity)
        {
            this.SendPropertyChanging("Problems");
            entity.VisitEncounter = this;
        }
    
        private void detach_Problems(Problem entity)
        {
            this.SendPropertyChanging("Problems");
            entity.VisitEncounter = null;
        }
    }

}
