//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 9/8/2016 11:57:11 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// All measurements, including labs and vitals
    /// </summary>
    [Table(Name = @"public.measurement")]
    public partial class Measurement : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private string _EmrIdentifier;

        private string _Name;

        private string _Description;

        private string _Comments;

        private CodedEntry _MeasurementCode;

        private System.Nullable<System.DateTime> _AssessmentDateTime;

        private string _Value;

        private string _Units;

        private string _NormalRangeLow;

        private string _NormalRangeHigh;

        private System.Nullable<ResultNormal> _NormalType;

        private long _Patientdbid;

        private System.Nullable<long> _VisitEncounterdbid;

        private System.DateTime _UpdateTime;

        private string _LastImportFileDate;

        private System.Nullable<System.DateTimeOffset> _BC_StartDateTime;

        private System.Nullable<System.DateTimeOffset> _BC_EndDateTime;

        private System.Nullable<System.DateTimeOffset> _BC_PerformedDateTime;

        private System.Nullable<System.DateTimeOffset> _BC_VerifiedDateTime;

        private System.Nullable<System.DateTimeOffset> _BC_AdministrationStartDateTime;

        private System.Nullable<System.DateTimeOffset> _BC_AdministrationEndDateTime;

        private System.Nullable<System.DateTimeOffset> _BC_ExpireDateTime;

        private System.Nullable<System.DateTimeOffset> _BC_EffectiveBeginDateTime;

        private System.Nullable<System.DateTimeOffset> _BC_EffectiveEndDateTime;

        private System.Nullable<System.DateTimeOffset> _BC_UpdateDateTime;
        #pragma warning restore 0649

        private EntityRef<Patient> _Patient;

        private EntityRef<VisitEncounter> _VisitEncounter;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnEmrIdentifierChanging(string value);
        partial void OnEmrIdentifierChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        partial void OnMeasurementCodeChanging(CodedEntry value);
        partial void OnMeasurementCodeChanged();
        partial void OnAssessmentDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnAssessmentDateTimeChanged();
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        partial void OnUnitsChanging(string value);
        partial void OnUnitsChanged();
        partial void OnNormalRangeLowChanging(string value);
        partial void OnNormalRangeLowChanged();
        partial void OnNormalRangeHighChanging(string value);
        partial void OnNormalRangeHighChanged();
        partial void OnNormalTypeChanging(System.Nullable<ResultNormal> value);
        partial void OnNormalTypeChanged();
        partial void OnPatientdbidChanging(long value);
        partial void OnPatientdbidChanged();
        partial void OnVisitEncounterdbidChanging(System.Nullable<long> value);
        partial void OnVisitEncounterdbidChanged();
        partial void OnUpdateTimeChanging(System.DateTime value);
        partial void OnUpdateTimeChanged();
        partial void OnLastImportFileDateChanging(string value);
        partial void OnLastImportFileDateChanged();
        partial void OnBC_StartDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnBC_StartDateTimeChanged();
        partial void OnBC_EndDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnBC_EndDateTimeChanged();
        partial void OnBC_PerformedDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnBC_PerformedDateTimeChanged();
        partial void OnBC_VerifiedDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnBC_VerifiedDateTimeChanged();
        partial void OnBC_AdministrationStartDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnBC_AdministrationStartDateTimeChanged();
        partial void OnBC_AdministrationEndDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnBC_AdministrationEndDateTimeChanged();
        partial void OnBC_ExpireDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnBC_ExpireDateTimeChanged();
        partial void OnBC_EffectiveBeginDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnBC_EffectiveBeginDateTimeChanged();
        partial void OnBC_EffectiveEndDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnBC_EffectiveEndDateTimeChanged();
        partial void OnBC_UpdateDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnBC_UpdateDateTimeChanged();
        #endregion

        public Measurement()
        {
            this._MeasurementCode = new CodedEntry();
            this._Patient  = default(EntityRef<Patient>);
            this._VisitEncounter  = default(EntityRef<VisitEncounter>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for EmrIdentifier in the schema.
        /// </summary>
        [Column(Name = @"emridentifier", Storage = "_EmrIdentifier", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string EmrIdentifier
        {
            get
            {
                return this._EmrIdentifier;
            }
            set
            {
                if (this._EmrIdentifier != value)
                {
                    this.OnEmrIdentifierChanging(value);
                    this.SendPropertyChanging();
                    this._EmrIdentifier = value;
                    this.SendPropertyChanged("EmrIdentifier");
                    this.OnEmrIdentifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Name = @"name", Storage = "_Name", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging();
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        [Column(Name = @"description", Storage = "_Description", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if (this._Description != value)
                {
                    this.OnDescriptionChanging(value);
                    this.SendPropertyChanging();
                    this._Description = value;
                    this.SendPropertyChanged("Description");
                    this.OnDescriptionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        [Column(Name = @"comments", Storage = "_Comments", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                if (this._Comments != value)
                {
                    this.OnCommentsChanging(value);
                    this.SendPropertyChanging();
                    this._Comments = value;
                    this.SendPropertyChanged("Comments");
                    this.OnCommentsChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MeasurementCode in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.ValueTypeProperty()]
        [Devart.Data.Linq.Mapping.Column(Member = "Code", Name = @"code", Storage = "_Code", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystem", Name = @"codesystem", Storage = "_CodeSystem", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystemVersion", Name = @"codesystemversion", Storage = "_CodeSystemVersion", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeMeaning", Name = @"codemeaning", Storage = "_CodeMeaning", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeModifier", Name = @"codemodifier", Storage = "_CodeModifier", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeModifierDescription", Name = @"codemodifierdescription", Storage = "_CodeModifierDescription", DbType = "varchar")]
        public CodedEntry MeasurementCode
        {
            get
            {
                return this._MeasurementCode;
            }
            set
            {
                if (this._MeasurementCode != value)
                {
                    this.OnMeasurementCodeChanging(value);
                    this.SendPropertyChanging();
                    this._MeasurementCode = value;
                    this.SendPropertyChanged("MeasurementCode");
                    this.OnMeasurementCodeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for AssessmentDateTime in the schema.
        /// </summary>
        [Column(Name = @"assessmentdatetime", Storage = "_AssessmentDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> AssessmentDateTime
        {
            get
            {
                return this._AssessmentDateTime;
            }
            set
            {
                if (this._AssessmentDateTime != value)
                {
                    this.OnAssessmentDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._AssessmentDateTime = value;
                    this.SendPropertyChanged("AssessmentDateTime");
                    this.OnAssessmentDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Value in the schema.
        /// </summary>
        [Column(Name = @"value", Storage = "_Value", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                if (this._Value != value)
                {
                    this.OnValueChanging(value);
                    this.SendPropertyChanging();
                    this._Value = value;
                    this.SendPropertyChanged("Value");
                    this.OnValueChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Units in the schema.
        /// </summary>
        [Column(Name = @"units", Storage = "_Units", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Units
        {
            get
            {
                return this._Units;
            }
            set
            {
                if (this._Units != value)
                {
                    this.OnUnitsChanging(value);
                    this.SendPropertyChanging();
                    this._Units = value;
                    this.SendPropertyChanged("Units");
                    this.OnUnitsChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NormalRangeLow in the schema.
        /// </summary>
        [Column(Name = @"normalrangelow", Storage = "_NormalRangeLow", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string NormalRangeLow
        {
            get
            {
                return this._NormalRangeLow;
            }
            set
            {
                if (this._NormalRangeLow != value)
                {
                    this.OnNormalRangeLowChanging(value);
                    this.SendPropertyChanging();
                    this._NormalRangeLow = value;
                    this.SendPropertyChanged("NormalRangeLow");
                    this.OnNormalRangeLowChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NormalRangeHigh in the schema.
        /// </summary>
        [Column(Name = @"normalrangehigh", Storage = "_NormalRangeHigh", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string NormalRangeHigh
        {
            get
            {
                return this._NormalRangeHigh;
            }
            set
            {
                if (this._NormalRangeHigh != value)
                {
                    this.OnNormalRangeHighChanging(value);
                    this.SendPropertyChanging();
                    this._NormalRangeHigh = value;
                    this.SendPropertyChanged("NormalRangeHigh");
                    this.OnNormalRangeHighChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NormalType in the schema.
        /// </summary>
        [Column(Name = @"normaltype", Storage = "_NormalType", DbType = "smallint", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<ResultNormal> NormalType
        {
            get
            {
                return this._NormalType;
            }
            set
            {
                if (this._NormalType != value)
                {
                    this.OnNormalTypeChanging(value);
                    this.SendPropertyChanging();
                    this._NormalType = value;
                    this.SendPropertyChanged("NormalType");
                    this.OnNormalTypeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patientdbid in the schema.
        /// </summary>
        [Column(Name = @"patientdbid", Storage = "_Patientdbid", AutoSync = AutoSync.Always, CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Patientdbid
        {
            get
            {
                return this._Patientdbid;
            }
            set
            {
                if (this._Patientdbid != value)
                {
                    if (this._Patient.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnPatientdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Patientdbid = value;
                    this.SendPropertyChanged("Patientdbid");
                    this.OnPatientdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounterdbid in the schema.
        /// </summary>
        [Column(Name = @"visitencounterdbid", Storage = "_VisitEncounterdbid", AutoSync = AutoSync.Always, DbType = "int8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> VisitEncounterdbid
        {
            get
            {
                return this._VisitEncounterdbid;
            }
            set
            {
                if (this._VisitEncounterdbid != value)
                {
                    if (this._VisitEncounter.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnVisitEncounterdbidChanging(value);
                    this.SendPropertyChanging();
                    this._VisitEncounterdbid = value;
                    this.SendPropertyChanged("VisitEncounterdbid");
                    this.OnVisitEncounterdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for UpdateTime in the schema.
        /// </summary>
        [Column(Name = @"updatetime", Storage = "_UpdateTime", CanBeNull = false, DbType = "timestamp NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime UpdateTime
        {
            get
            {
                return this._UpdateTime;
            }
            set
            {
                if (this._UpdateTime != value)
                {
                    this.OnUpdateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._UpdateTime = value;
                    this.SendPropertyChanged("UpdateTime");
                    this.OnUpdateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for LastImportFileDate in the schema.
        /// </summary>
        [Column(Name = @"lastimportfiledate", Storage = "_LastImportFileDate", CanBeNull = false, DbType = "varchar NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string LastImportFileDate
        {
            get
            {
                return this._LastImportFileDate;
            }
            set
            {
                if (this._LastImportFileDate != value)
                {
                    this.OnLastImportFileDateChanging(value);
                    this.SendPropertyChanging();
                    this._LastImportFileDate = value;
                    this.SendPropertyChanged("LastImportFileDate");
                    this.OnLastImportFileDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BC_StartDateTime in the schema.
        /// </summary>
        [Column(Name = @"bc_startdatetime", Storage = "_BC_StartDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> BC_StartDateTime
        {
            get
            {
                return this._BC_StartDateTime;
            }
            set
            {
                if (this._BC_StartDateTime != value)
                {
                    this.OnBC_StartDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BC_StartDateTime = value;
                    this.SendPropertyChanged("BC_StartDateTime");
                    this.OnBC_StartDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BC_EndDateTime in the schema.
        /// </summary>
        [Column(Name = @"bc_enddatetime", Storage = "_BC_EndDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> BC_EndDateTime
        {
            get
            {
                return this._BC_EndDateTime;
            }
            set
            {
                if (this._BC_EndDateTime != value)
                {
                    this.OnBC_EndDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BC_EndDateTime = value;
                    this.SendPropertyChanged("BC_EndDateTime");
                    this.OnBC_EndDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BC_PerformedDateTime in the schema.
        /// </summary>
        [Column(Name = @"bc_performeddatetime", Storage = "_BC_PerformedDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> BC_PerformedDateTime
        {
            get
            {
                return this._BC_PerformedDateTime;
            }
            set
            {
                if (this._BC_PerformedDateTime != value)
                {
                    this.OnBC_PerformedDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BC_PerformedDateTime = value;
                    this.SendPropertyChanged("BC_PerformedDateTime");
                    this.OnBC_PerformedDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BC_VerifiedDateTime in the schema.
        /// </summary>
        [Column(Name = @"bc_verifieddatetime", Storage = "_BC_VerifiedDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> BC_VerifiedDateTime
        {
            get
            {
                return this._BC_VerifiedDateTime;
            }
            set
            {
                if (this._BC_VerifiedDateTime != value)
                {
                    this.OnBC_VerifiedDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BC_VerifiedDateTime = value;
                    this.SendPropertyChanged("BC_VerifiedDateTime");
                    this.OnBC_VerifiedDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BC_AdministrationStartDateTime in the schema.
        /// </summary>
        [Column(Name = @"bc_administrationstartdatetime", Storage = "_BC_AdministrationStartDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> BC_AdministrationStartDateTime
        {
            get
            {
                return this._BC_AdministrationStartDateTime;
            }
            set
            {
                if (this._BC_AdministrationStartDateTime != value)
                {
                    this.OnBC_AdministrationStartDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BC_AdministrationStartDateTime = value;
                    this.SendPropertyChanged("BC_AdministrationStartDateTime");
                    this.OnBC_AdministrationStartDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BC_AdministrationEndDateTime in the schema.
        /// </summary>
        [Column(Name = @"bc_administrationenddatetime", Storage = "_BC_AdministrationEndDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> BC_AdministrationEndDateTime
        {
            get
            {
                return this._BC_AdministrationEndDateTime;
            }
            set
            {
                if (this._BC_AdministrationEndDateTime != value)
                {
                    this.OnBC_AdministrationEndDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BC_AdministrationEndDateTime = value;
                    this.SendPropertyChanged("BC_AdministrationEndDateTime");
                    this.OnBC_AdministrationEndDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BC_ExpireDateTime in the schema.
        /// </summary>
        [Column(Name = @"bc_expiredatetime", Storage = "_BC_ExpireDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> BC_ExpireDateTime
        {
            get
            {
                return this._BC_ExpireDateTime;
            }
            set
            {
                if (this._BC_ExpireDateTime != value)
                {
                    this.OnBC_ExpireDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BC_ExpireDateTime = value;
                    this.SendPropertyChanged("BC_ExpireDateTime");
                    this.OnBC_ExpireDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BC_EffectiveBeginDateTime in the schema.
        /// </summary>
        [Column(Name = @"bc_effectivebegindatetime", Storage = "_BC_EffectiveBeginDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> BC_EffectiveBeginDateTime
        {
            get
            {
                return this._BC_EffectiveBeginDateTime;
            }
            set
            {
                if (this._BC_EffectiveBeginDateTime != value)
                {
                    this.OnBC_EffectiveBeginDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BC_EffectiveBeginDateTime = value;
                    this.SendPropertyChanged("BC_EffectiveBeginDateTime");
                    this.OnBC_EffectiveBeginDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BC_EffectiveEndDateTime in the schema.
        /// </summary>
        [Column(Name = @"bc_effectiveenddatetime", Storage = "_BC_EffectiveEndDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> BC_EffectiveEndDateTime
        {
            get
            {
                return this._BC_EffectiveEndDateTime;
            }
            set
            {
                if (this._BC_EffectiveEndDateTime != value)
                {
                    this.OnBC_EffectiveEndDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BC_EffectiveEndDateTime = value;
                    this.SendPropertyChanged("BC_EffectiveEndDateTime");
                    this.OnBC_EffectiveEndDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BC_UpdateDateTime in the schema.
        /// </summary>
        [Column(Name = @"bc_updatedatetime", Storage = "_BC_UpdateDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> BC_UpdateDateTime
        {
            get
            {
                return this._BC_UpdateDateTime;
            }
            set
            {
                if (this._BC_UpdateDateTime != value)
                {
                    this.OnBC_UpdateDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BC_UpdateDateTime = value;
                    this.SendPropertyChanged("BC_UpdateDateTime");
                    this.OnBC_UpdateDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Measurement", Storage="_Patient", ThisKey="Patientdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Patient Patient
        {
            get
            {
                return this._Patient.Entity;
            }
            set
            {
                Patient previousValue = this._Patient.Entity;
                if ((previousValue != value) || (this._Patient.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Patient.Entity = null;
                        previousValue.Measurements.Remove(this);
                    }
                    this._Patient.Entity = value;
                    if (value != null)
                    {
                        this._Patientdbid = value.dbid;
                        value.Measurements.Add(this);
                    }
                    else
                    {
                        this._Patientdbid = default(long);
                    }
                    this.SendPropertyChanged("Patient");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounter in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Measurement", Storage="_VisitEncounter", ThisKey="VisitEncounterdbid", OtherKey="dbid", IsForeignKey=true)]
        public VisitEncounter VisitEncounter
        {
            get
            {
                return this._VisitEncounter.Entity;
            }
            set
            {
                VisitEncounter previousValue = this._VisitEncounter.Entity;
                if ((previousValue != value) || (this._VisitEncounter.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._VisitEncounter.Entity = null;
                        previousValue.Results.Remove(this);
                    }
                    this._VisitEncounter.Entity = value;
                    if (value != null)
                    {
                        this._VisitEncounterdbid = value.dbid;
                        value.Results.Add(this);
                    }
                    else
                    {
                        this._VisitEncounterdbid = default(System.Nullable<long>);
                    }
                    this.SendPropertyChanged("VisitEncounter");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
