//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 6/28/2016 3:21:46 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for PhoneType in the schema.
    /// </summary>
    public enum PhoneType : short
    {
    
        /// <summary>
        /// There are no comments for PhoneType.Unspecified in the schema.
        /// </summary>
        Unspecified,    
        /// <summary>
        /// There are no comments for PhoneType.Home in the schema.
        /// </summary>
        Home,    
        /// <summary>
        /// There are no comments for PhoneType.Work in the schema.
        /// </summary>
        Work,    
        /// <summary>
        /// There are no comments for PhoneType.Mobile in the schema.
        /// </summary>
        Mobile,    
        /// <summary>
        /// There are no comments for PhoneType.Fax in the schema.
        /// </summary>
        Fax,    
        /// <summary>
        /// There are no comments for PhoneType.Other in the schema.
        /// </summary>
        Other
    }

}
