//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 6/28/2016 9:44:39 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CodedEntry in the schema.
    /// </summary>
    public partial class CodedEntry: INotifyPropertyChanging, INotifyPropertyChanged    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private string _Code;

        private string _CodeSystem;

        private string _CodeSystemVersion;

        private string _CodeMeaning;

        private string _CodeModifier;

        private string _CodeModifierDescription;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        partial void OnCodeSystemChanging(string value);
        partial void OnCodeSystemChanged();
        partial void OnCodeSystemVersionChanging(string value);
        partial void OnCodeSystemVersionChanged();
        partial void OnCodeMeaningChanging(string value);
        partial void OnCodeMeaningChanged();
        partial void OnCodeModifierChanging(string value);
        partial void OnCodeModifierChanged();
        partial void OnCodeModifierDescriptionChanging(string value);
        partial void OnCodeModifierDescriptionChanged();
        #endregion

        public CodedEntry()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Code in the schema.
        /// </summary>
        [Column(Name = @"code", Storage = "_Code", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                if (this._Code != value)
                {
                    this.OnCodeChanging(value);
                    this.SendPropertyChanging();
                    this._Code = value;
                    this.SendPropertyChanged("Code");
                    this.OnCodeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for CodeSystem in the schema.
        /// </summary>
        [Column(Name = @"codesystem", Storage = "_CodeSystem", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string CodeSystem
        {
            get
            {
                return this._CodeSystem;
            }
            set
            {
                if (this._CodeSystem != value)
                {
                    this.OnCodeSystemChanging(value);
                    this.SendPropertyChanging();
                    this._CodeSystem = value;
                    this.SendPropertyChanged("CodeSystem");
                    this.OnCodeSystemChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for CodeSystemVersion in the schema.
        /// </summary>
        [Column(Name = @"codesystemversion", Storage = "_CodeSystemVersion", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string CodeSystemVersion
        {
            get
            {
                return this._CodeSystemVersion;
            }
            set
            {
                if (this._CodeSystemVersion != value)
                {
                    this.OnCodeSystemVersionChanging(value);
                    this.SendPropertyChanging();
                    this._CodeSystemVersion = value;
                    this.SendPropertyChanged("CodeSystemVersion");
                    this.OnCodeSystemVersionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for CodeMeaning in the schema.
        /// </summary>
        [Column(Name = @"codemeaning", Storage = "_CodeMeaning", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string CodeMeaning
        {
            get
            {
                return this._CodeMeaning;
            }
            set
            {
                if (this._CodeMeaning != value)
                {
                    this.OnCodeMeaningChanging(value);
                    this.SendPropertyChanging();
                    this._CodeMeaning = value;
                    this.SendPropertyChanged("CodeMeaning");
                    this.OnCodeMeaningChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for CodeModifier in the schema.
        /// </summary>
        [Column(Name = @"codemodifier", Storage = "_CodeModifier", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string CodeModifier
        {
            get
            {
                return this._CodeModifier;
            }
            set
            {
                if (this._CodeModifier != value)
                {
                    this.OnCodeModifierChanging(value);
                    this.SendPropertyChanging();
                    this._CodeModifier = value;
                    this.SendPropertyChanged("CodeModifier");
                    this.OnCodeModifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for CodeModifierDescription in the schema.
        /// </summary>
        [Column(Name = @"codemodifierdescription", Storage = "_CodeModifierDescription", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string CodeModifierDescription
        {
            get
            {
                return this._CodeModifierDescription;
            }
            set
            {
                if (this._CodeModifierDescription != value)
                {
                    this.OnCodeModifierDescriptionChanging(value);
                    this.SendPropertyChanging();
                    this._CodeModifierDescription = value;
                    this.SendPropertyChanged("CodeModifierDescription");
                    this.OnCodeModifierDescriptionChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
