//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 8/26/2016 8:51:50 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.Problem in the schema.
    /// </summary>
    [Table(Name = @"public.problem")]
    public partial class Problem : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private string _EmrIdentifier;

        private string _Description;

        private System.Nullable<System.DateTime> _EffectiveDateTime;

        private System.Nullable<System.DateTime> _BeginDateTime;

        private System.Nullable<System.DateTime> _EndDateTime;

        private long _Patientdbid;

        private System.Nullable<long> _VisitEncounterdbid;

        private System.DateTime _UpdateTime;

        private string _LastImportFileDate;
        #pragma warning restore 0649

        private EntityRef<Patient> _Patient;

        private EntityRef<VisitEncounter> _VisitEncounter;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnEmrIdentifierChanging(string value);
        partial void OnEmrIdentifierChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        partial void OnEffectiveDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnEffectiveDateTimeChanged();
        partial void OnBeginDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnBeginDateTimeChanged();
        partial void OnEndDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnEndDateTimeChanged();
        partial void OnPatientdbidChanging(long value);
        partial void OnPatientdbidChanged();
        partial void OnVisitEncounterdbidChanging(System.Nullable<long> value);
        partial void OnVisitEncounterdbidChanged();
        partial void OnUpdateTimeChanging(System.DateTime value);
        partial void OnUpdateTimeChanged();
        partial void OnLastImportFileDateChanging(string value);
        partial void OnLastImportFileDateChanged();
        #endregion

        public Problem()
        {
            this._Patient  = default(EntityRef<Patient>);
            this._VisitEncounter  = default(EntityRef<VisitEncounter>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for EmrIdentifier in the schema.
        /// </summary>
        [Column(Name = @"emridentifier", Storage = "_EmrIdentifier", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string EmrIdentifier
        {
            get
            {
                return this._EmrIdentifier;
            }
            set
            {
                if (this._EmrIdentifier != value)
                {
                    this.OnEmrIdentifierChanging(value);
                    this.SendPropertyChanging();
                    this._EmrIdentifier = value;
                    this.SendPropertyChanged("EmrIdentifier");
                    this.OnEmrIdentifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        [Column(Name = @"description", Storage = "_Description", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if (this._Description != value)
                {
                    this.OnDescriptionChanging(value);
                    this.SendPropertyChanging();
                    this._Description = value;
                    this.SendPropertyChanged("Description");
                    this.OnDescriptionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EffectiveDateTime in the schema.
        /// </summary>
        [Column(Name = @"effectivedatetime", Storage = "_EffectiveDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> EffectiveDateTime
        {
            get
            {
                return this._EffectiveDateTime;
            }
            set
            {
                if (this._EffectiveDateTime != value)
                {
                    this.OnEffectiveDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._EffectiveDateTime = value;
                    this.SendPropertyChanged("EffectiveDateTime");
                    this.OnEffectiveDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BeginDateTime in the schema.
        /// </summary>
        [Column(Name = @"begindatetime", Storage = "_BeginDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> BeginDateTime
        {
            get
            {
                return this._BeginDateTime;
            }
            set
            {
                if (this._BeginDateTime != value)
                {
                    this.OnBeginDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._BeginDateTime = value;
                    this.SendPropertyChanged("BeginDateTime");
                    this.OnBeginDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EndDateTime in the schema.
        /// </summary>
        [Column(Name = @"enddatetime", Storage = "_EndDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> EndDateTime
        {
            get
            {
                return this._EndDateTime;
            }
            set
            {
                if (this._EndDateTime != value)
                {
                    this.OnEndDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._EndDateTime = value;
                    this.SendPropertyChanged("EndDateTime");
                    this.OnEndDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patientdbid in the schema.
        /// </summary>
        [Column(Name = @"patientdbid", Storage = "_Patientdbid", AutoSync = AutoSync.Always, CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Patientdbid
        {
            get
            {
                return this._Patientdbid;
            }
            set
            {
                if (this._Patientdbid != value)
                {
                    if (this._Patient.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnPatientdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Patientdbid = value;
                    this.SendPropertyChanged("Patientdbid");
                    this.OnPatientdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounterdbid in the schema.
        /// </summary>
        [Column(Name = @"visitencounterdbid", Storage = "_VisitEncounterdbid", AutoSync = AutoSync.Always, DbType = "int8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> VisitEncounterdbid
        {
            get
            {
                return this._VisitEncounterdbid;
            }
            set
            {
                if (this._VisitEncounterdbid != value)
                {
                    if (this._VisitEncounter.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnVisitEncounterdbidChanging(value);
                    this.SendPropertyChanging();
                    this._VisitEncounterdbid = value;
                    this.SendPropertyChanged("VisitEncounterdbid");
                    this.OnVisitEncounterdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for UpdateTime in the schema.
        /// </summary>
        [Column(Name = @"updatetime", Storage = "_UpdateTime", CanBeNull = false, DbType = "timestamp NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime UpdateTime
        {
            get
            {
                return this._UpdateTime;
            }
            set
            {
                if (this._UpdateTime != value)
                {
                    this.OnUpdateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._UpdateTime = value;
                    this.SendPropertyChanged("UpdateTime");
                    this.OnUpdateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for LastImportFileDate in the schema.
        /// </summary>
        [Column(Name = @"lastimportfiledate", Storage = "_LastImportFileDate", CanBeNull = false, DbType = "varchar NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string LastImportFileDate
        {
            get
            {
                return this._LastImportFileDate;
            }
            set
            {
                if (this._LastImportFileDate != value)
                {
                    this.OnLastImportFileDateChanging(value);
                    this.SendPropertyChanging();
                    this._LastImportFileDate = value;
                    this.SendPropertyChanged("LastImportFileDate");
                    this.OnLastImportFileDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Problem", Storage="_Patient", ThisKey="Patientdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Patient Patient
        {
            get
            {
                return this._Patient.Entity;
            }
            set
            {
                Patient previousValue = this._Patient.Entity;
                if ((previousValue != value) || (this._Patient.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Patient.Entity = null;
                        previousValue.Problems.Remove(this);
                    }
                    this._Patient.Entity = value;
                    if (value != null)
                    {
                        this._Patientdbid = value.dbid;
                        value.Problems.Add(this);
                    }
                    else
                    {
                        this._Patientdbid = default(long);
                    }
                    this.SendPropertyChanged("Patient");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounter in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Problem", Storage="_VisitEncounter", ThisKey="VisitEncounterdbid", OtherKey="dbid", IsForeignKey=true)]
        public VisitEncounter VisitEncounter
        {
            get
            {
                return this._VisitEncounter.Entity;
            }
            set
            {
                VisitEncounter previousValue = this._VisitEncounter.Entity;
                if ((previousValue != value) || (this._VisitEncounter.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._VisitEncounter.Entity = null;
                        previousValue.Problems.Remove(this);
                    }
                    this._VisitEncounter.Entity = value;
                    if (value != null)
                    {
                        this._VisitEncounterdbid = value.dbid;
                        value.Problems.Add(this);
                    }
                    else
                    {
                        this._VisitEncounterdbid = default(System.Nullable<long>);
                    }
                    this.SendPropertyChanged("VisitEncounter");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
