//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 5/18/2016 1:56:19 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.Medication in the schema.
    /// </summary>
    [Table(Name = @"public.medication")]
    public partial class Medication : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private string _EmrIdentifier;

        private CodedEntry _Code;

        private System.Nullable<System.DateTimeOffset> _PrescriptionDate;

        private System.Nullable<System.DateTimeOffset> _FillDate;

        private string _Instructions;

        private string _Description;

        private System.Nullable<System.DateTimeOffset> _StartDate;

        private System.Nullable<System.DateTimeOffset> _StopDate;

        private string _Status;

        private System.Nullable<System.DateTimeOffset> _StatusDateTime;

        private long _Patientdbid;

        private System.Nullable<long> _VisitEncounterdbid;
        #pragma warning restore 0649

        private EntityRef<Patient> _Patient;

        private EntityRef<VisitEncounter> _VisitEncounter;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnEmrIdentifierChanging(string value);
        partial void OnEmrIdentifierChanged();
        partial void OnCodeChanging(CodedEntry value);
        partial void OnCodeChanged();
        partial void OnPrescriptionDateChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnPrescriptionDateChanged();
        partial void OnFillDateChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnFillDateChanged();
        partial void OnInstructionsChanging(string value);
        partial void OnInstructionsChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        partial void OnStartDateChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnStartDateChanged();
        partial void OnStopDateChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnStopDateChanged();
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        partial void OnStatusDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
        partial void OnStatusDateTimeChanged();
        partial void OnPatientdbidChanging(long value);
        partial void OnPatientdbidChanged();
        partial void OnVisitEncounterdbidChanging(System.Nullable<long> value);
        partial void OnVisitEncounterdbidChanged();
        #endregion

        public Medication()
        {
            this._Code = new CodedEntry();
            this._Patient  = default(EntityRef<Patient>);
            this._VisitEncounter  = default(EntityRef<VisitEncounter>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for EmrIdentifier in the schema.
        /// </summary>
        [Column(Name = @"emridentifier", Storage = "_EmrIdentifier", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string EmrIdentifier
        {
            get
            {
                return this._EmrIdentifier;
            }
            set
            {
                if (this._EmrIdentifier != value)
                {
                    this.OnEmrIdentifierChanging(value);
                    this.SendPropertyChanging();
                    this._EmrIdentifier = value;
                    this.SendPropertyChanged("EmrIdentifier");
                    this.OnEmrIdentifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Code in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.ValueTypeProperty()]
        [Devart.Data.Linq.Mapping.Column(Member = "Code", Name = @"code", Storage = "_Code", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystem", Name = @"codesystem", Storage = "_CodeSystem", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystemVersion", Name = @"codesystemversion", Storage = "_CodeSystemVersion", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeMeaning", Name = @"codemeaning", Storage = "_CodeMeaning", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeModifier", Name = @"codemodifier", Storage = "_CodeModifier", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeModifierDescription", Name = @"codemodifierdescription", Storage = "_CodeModifierDescription", DbType = "varchar")]
        public CodedEntry Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                if (this._Code != value)
                {
                    this.OnCodeChanging(value);
                    this.SendPropertyChanging();
                    this._Code = value;
                    this.SendPropertyChanged("Code");
                    this.OnCodeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PrescriptionDate in the schema.
        /// </summary>
        [Column(Name = @"prescriptiondate", Storage = "_PrescriptionDate", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> PrescriptionDate
        {
            get
            {
                return this._PrescriptionDate;
            }
            set
            {
                if (this._PrescriptionDate != value)
                {
                    this.OnPrescriptionDateChanging(value);
                    this.SendPropertyChanging();
                    this._PrescriptionDate = value;
                    this.SendPropertyChanged("PrescriptionDate");
                    this.OnPrescriptionDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for FillDate in the schema.
        /// </summary>
        [Column(Name = @"filldate", Storage = "_FillDate", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> FillDate
        {
            get
            {
                return this._FillDate;
            }
            set
            {
                if (this._FillDate != value)
                {
                    this.OnFillDateChanging(value);
                    this.SendPropertyChanging();
                    this._FillDate = value;
                    this.SendPropertyChanged("FillDate");
                    this.OnFillDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Instructions in the schema.
        /// </summary>
        [Column(Name = @"instructions", Storage = "_Instructions", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Instructions
        {
            get
            {
                return this._Instructions;
            }
            set
            {
                if (this._Instructions != value)
                {
                    this.OnInstructionsChanging(value);
                    this.SendPropertyChanging();
                    this._Instructions = value;
                    this.SendPropertyChanged("Instructions");
                    this.OnInstructionsChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        [Column(Name = @"description", Storage = "_Description", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if (this._Description != value)
                {
                    this.OnDescriptionChanging(value);
                    this.SendPropertyChanging();
                    this._Description = value;
                    this.SendPropertyChanged("Description");
                    this.OnDescriptionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for StartDate in the schema.
        /// </summary>
        [Column(Name = @"startdate", Storage = "_StartDate", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                if (this._StartDate != value)
                {
                    this.OnStartDateChanging(value);
                    this.SendPropertyChanging();
                    this._StartDate = value;
                    this.SendPropertyChanged("StartDate");
                    this.OnStartDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for StopDate in the schema.
        /// </summary>
        [Column(Name = @"stopdate", Storage = "_StopDate", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> StopDate
        {
            get
            {
                return this._StopDate;
            }
            set
            {
                if (this._StopDate != value)
                {
                    this.OnStopDateChanging(value);
                    this.SendPropertyChanging();
                    this._StopDate = value;
                    this.SendPropertyChanged("StopDate");
                    this.OnStopDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        [Column(Name = @"status", Storage = "_Status", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                if (this._Status != value)
                {
                    this.OnStatusChanging(value);
                    this.SendPropertyChanging();
                    this._Status = value;
                    this.SendPropertyChanged("Status");
                    this.OnStatusChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for StatusDateTime in the schema.
        /// </summary>
        [Column(Name = @"statusdatetime", Storage = "_StatusDateTime", DbType = "timestamp with time zone", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTimeOffset> StatusDateTime
        {
            get
            {
                return this._StatusDateTime;
            }
            set
            {
                if (this._StatusDateTime != value)
                {
                    this.OnStatusDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._StatusDateTime = value;
                    this.SendPropertyChanged("StatusDateTime");
                    this.OnStatusDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patientdbid in the schema.
        /// </summary>
        [Column(Name = @"patientdbid", Storage = "_Patientdbid", AutoSync = AutoSync.Always, CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Patientdbid
        {
            get
            {
                return this._Patientdbid;
            }
            set
            {
                if (this._Patientdbid != value)
                {
                    if (this._Patient.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnPatientdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Patientdbid = value;
                    this.SendPropertyChanged("Patientdbid");
                    this.OnPatientdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounterdbid in the schema.
        /// </summary>
        [Column(Name = @"visitencounterdbid", Storage = "_VisitEncounterdbid", AutoSync = AutoSync.Always, DbType = "int8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> VisitEncounterdbid
        {
            get
            {
                return this._VisitEncounterdbid;
            }
            set
            {
                if (this._VisitEncounterdbid != value)
                {
                    if (this._VisitEncounter.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnVisitEncounterdbidChanging(value);
                    this.SendPropertyChanging();
                    this._VisitEncounterdbid = value;
                    this.SendPropertyChanged("VisitEncounterdbid");
                    this.OnVisitEncounterdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Medication", Storage="_Patient", ThisKey="Patientdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Patient Patient
        {
            get
            {
                return this._Patient.Entity;
            }
            set
            {
                Patient previousValue = this._Patient.Entity;
                if ((previousValue != value) || (this._Patient.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Patient.Entity = null;
                        previousValue.Medications.Remove(this);
                    }
                    this._Patient.Entity = value;
                    if (value != null)
                    {
                        this._Patientdbid = value.dbid;
                        value.Medications.Add(this);
                    }
                    else
                    {
                        this._Patientdbid = default(long);
                    }
                    this.SendPropertyChanged("Patient");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounter in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Medication", Storage="_VisitEncounter", ThisKey="VisitEncounterdbid", OtherKey="dbid", IsForeignKey=true)]
        public VisitEncounter VisitEncounter
        {
            get
            {
                return this._VisitEncounter.Entity;
            }
            set
            {
                VisitEncounter previousValue = this._VisitEncounter.Entity;
                if ((previousValue != value) || (this._VisitEncounter.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._VisitEncounter.Entity = null;
                        previousValue.Medications.Remove(this);
                    }
                    this._VisitEncounter.Entity = value;
                    if (value != null)
                    {
                        this._VisitEncounterdbid = value.dbid;
                        value.Medications.Add(this);
                    }
                    else
                    {
                        this._VisitEncounterdbid = default(System.Nullable<long>);
                    }
                    this.SendPropertyChanged("VisitEncounter");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
