//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 6/24/2016 1:35:18 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.Immunization in the schema.
    /// </summary>
    [Table(Name = @"public.immunization")]
    public partial class Immunization : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _bdid;

        private string _EmrIdentifier;

        private string _Description;

        private System.Nullable<System.DateTime> _PerformedDateTime;

        private CodedEntry _ImmunizationCode;

        private long _Patientdbid;

        private System.Nullable<long> _VisitEncounterdbid;
        #pragma warning restore 0649

        private EntityRef<Patient> _Patient;

        private EntityRef<VisitEncounter> _VisitEncounter;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnbdidChanging(long value);
        partial void OnbdidChanged();
        partial void OnEmrIdentifierChanging(string value);
        partial void OnEmrIdentifierChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        partial void OnPerformedDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnPerformedDateTimeChanged();
        partial void OnImmunizationCodeChanging(CodedEntry value);
        partial void OnImmunizationCodeChanged();
        partial void OnPatientdbidChanging(long value);
        partial void OnPatientdbidChanged();
        partial void OnVisitEncounterdbidChanging(System.Nullable<long> value);
        partial void OnVisitEncounterdbidChanged();
        #endregion

        public Immunization()
        {
            this._ImmunizationCode = new CodedEntry();
            this._Patient  = default(EntityRef<Patient>);
            this._VisitEncounter  = default(EntityRef<VisitEncounter>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for bdid in the schema.
        /// </summary>
        [Column(Storage = "_bdid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long bdid
        {
            get
            {
                return this._bdid;
            }
        }

    
        /// <summary>
        /// There are no comments for EmrIdentifier in the schema.
        /// </summary>
        [Column(Name = @"emridentifier", Storage = "_EmrIdentifier", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string EmrIdentifier
        {
            get
            {
                return this._EmrIdentifier;
            }
            set
            {
                if (this._EmrIdentifier != value)
                {
                    this.OnEmrIdentifierChanging(value);
                    this.SendPropertyChanging();
                    this._EmrIdentifier = value;
                    this.SendPropertyChanged("EmrIdentifier");
                    this.OnEmrIdentifierChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        [Column(Name = @"description", Storage = "_Description", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if (this._Description != value)
                {
                    this.OnDescriptionChanging(value);
                    this.SendPropertyChanging();
                    this._Description = value;
                    this.SendPropertyChanged("Description");
                    this.OnDescriptionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PerformedDateTime in the schema.
        /// </summary>
        [Column(Name = @"performeddatetime", Storage = "_PerformedDateTime", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> PerformedDateTime
        {
            get
            {
                return this._PerformedDateTime;
            }
            set
            {
                if (this._PerformedDateTime != value)
                {
                    this.OnPerformedDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._PerformedDateTime = value;
                    this.SendPropertyChanged("PerformedDateTime");
                    this.OnPerformedDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ImmunizationCode in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.ValueTypeProperty()]
        [Devart.Data.Linq.Mapping.Column(Member = "Code", Name = @"code", Storage = "_Code", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystem", Name = @"codesystem", Storage = "_CodeSystem", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeSystemVersion", Name = @"codesystemversion", Storage = "_CodeSystemVersion", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeMeaning", Name = @"codemeaning", Storage = "_CodeMeaning", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeModifier", Name = @"codemodifier", Storage = "_CodeModifier", DbType = "varchar")]
        [Devart.Data.Linq.Mapping.Column(Member = "CodeModifierDescription", Name = @"codemodifierdescription", Storage = "_CodeModifierDescription", DbType = "varchar")]
        public CodedEntry ImmunizationCode
        {
            get
            {
                return this._ImmunizationCode;
            }
            set
            {
                if (this._ImmunizationCode != value)
                {
                    this.OnImmunizationCodeChanging(value);
                    this.SendPropertyChanging();
                    this._ImmunizationCode = value;
                    this.SendPropertyChanged("ImmunizationCode");
                    this.OnImmunizationCodeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patientdbid in the schema.
        /// </summary>
        [Column(Name = @"patientdbid", Storage = "_Patientdbid", AutoSync = AutoSync.Always, CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long Patientdbid
        {
            get
            {
                return this._Patientdbid;
            }
            set
            {
                if (this._Patientdbid != value)
                {
                    if (this._Patient.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnPatientdbidChanging(value);
                    this.SendPropertyChanging();
                    this._Patientdbid = value;
                    this.SendPropertyChanged("Patientdbid");
                    this.OnPatientdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounterdbid in the schema.
        /// </summary>
        [Column(Name = @"visitencounterdbid", Storage = "_VisitEncounterdbid", AutoSync = AutoSync.Always, DbType = "int8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> VisitEncounterdbid
        {
            get
            {
                return this._VisitEncounterdbid;
            }
            set
            {
                if (this._VisitEncounterdbid != value)
                {
                    if (this._VisitEncounter.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnVisitEncounterdbidChanging(value);
                    this.SendPropertyChanging();
                    this._VisitEncounterdbid = value;
                    this.SendPropertyChanged("VisitEncounterdbid");
                    this.OnVisitEncounterdbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Patient_Immunization", Storage="_Patient", ThisKey="Patientdbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public Patient Patient
        {
            get
            {
                return this._Patient.Entity;
            }
            set
            {
                Patient previousValue = this._Patient.Entity;
                if ((previousValue != value) || (this._Patient.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Patient.Entity = null;
                        previousValue.Immunizations.Remove(this);
                    }
                    this._Patient.Entity = value;
                    if (value != null)
                    {
                        this._Patientdbid = value.dbid;
                        value.Immunizations.Add(this);
                    }
                    else
                    {
                        this._Patientdbid = default(long);
                    }
                    this.SendPropertyChanged("Patient");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VisitEncounter in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="VisitEncounter_Immunization", Storage="_VisitEncounter", ThisKey="VisitEncounterdbid", OtherKey="dbid", IsForeignKey=true)]
        public VisitEncounter VisitEncounter
        {
            get
            {
                return this._VisitEncounter.Entity;
            }
            set
            {
                VisitEncounter previousValue = this._VisitEncounter.Entity;
                if ((previousValue != value) || (this._VisitEncounter.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._VisitEncounter.Entity = null;
                        previousValue.Immunizations.Remove(this);
                    }
                    this._VisitEncounter.Entity = value;
                    if (value != null)
                    {
                        this._VisitEncounterdbid = value.dbid;
                        value.Immunizations.Add(this);
                    }
                    else
                    {
                        this._VisitEncounterdbid = default(System.Nullable<long>);
                    }
                    this.SendPropertyChanged("VisitEncounter");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
