//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 6/28/2016 1:26:41 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    /// <summary>
    /// There are no comments for CdrContext.AggregationRun in the schema.
    /// </summary>
    [Table(Name = @"public.aggregationrun")]
    public partial class AggregationRun : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private AggregationRunStatus _StatusFlags;

        private long _DataFeeddbid;
        #pragma warning restore 0649

        private EntityRef<DataFeed> _DataFeed;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnStatusFlagsChanging(AggregationRunStatus value);
        partial void OnStatusFlagsChanged();
        partial void OnDataFeeddbidChanging(long value);
        partial void OnDataFeeddbidChanged();
        #endregion

        public AggregationRun()
        {
            this._DataFeed  = default(EntityRef<DataFeed>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// Bit mask
        /// </summary>
        /// <LongDescription>
        /// Binary            Int     Meaning
        /// 00000001       1         Value Reserved By Program
        /// 00000010       2         Aggregation In Progress
        /// 00000100       4         Complete
        /// 00001000       8         future
        /// 00010000      16        future 
        /// 00100000      32         future
        /// 01000000      64         future
        /// 10000000     128         future
        /// 
        /// 
        /// 
        /// 
        /// 
        /// 
        /// </LongDescription>
        [Column(Name = @"statusflags", Storage = "_StatusFlags", CanBeNull = false, DbType = "int4 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public AggregationRunStatus StatusFlags
        {
            get
            {
                return this._StatusFlags;
            }
            set
            {
                if (this._StatusFlags != value)
                {
                    this.OnStatusFlagsChanging(value);
                    this.SendPropertyChanging();
                    this._StatusFlags = value;
                    this.SendPropertyChanged("StatusFlags");
                    this.OnStatusFlagsChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DataFeeddbid in the schema.
        /// </summary>
        [Column(Name = @"datafeeddbid", Storage = "_DataFeeddbid", CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long DataFeeddbid
        {
            get
            {
                return this._DataFeeddbid;
            }
            set
            {
                if (this._DataFeeddbid != value)
                {
                    if (this._DataFeed.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnDataFeeddbidChanging(value);
                    this.SendPropertyChanging();
                    this._DataFeeddbid = value;
                    this.SendPropertyChanged("DataFeeddbid");
                    this.OnDataFeeddbidChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DataFeed in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="DataFeed_AggregationRun", Storage="_DataFeed", ThisKey="DataFeeddbid", OtherKey="dbid", IsForeignKey=true, DeleteOnNull=true)]
        public DataFeed DataFeed
        {
            get
            {
                return this._DataFeed.Entity;
            }
            set
            {
                DataFeed previousValue = this._DataFeed.Entity;
                if ((previousValue != value) || (this._DataFeed.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._DataFeed.Entity = null;
                        previousValue.AggregationRuns.Remove(this);
                    }
                    this._DataFeed.Entity = value;
                    if (value != null)
                    {
                        this._DataFeeddbid = value.dbid;
                        value.AggregationRuns.Add(this);
                    }
                    else
                    {
                        this._DataFeeddbid = default(long);
                    }
                    this.SendPropertyChanged("DataFeed");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
