<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Summary.aspx.cs" Inherits="ClientPublisher.Summary" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>

<style type="text/css">
.tftable {font-size:12px;color:#333333;width:100%;border-width: 1px;border-color: #a9a9a9;border-collapse: collapse;width:580px}
.tftable th {font-size:12px;background-color:#F5F5F5;border-width: 1px;padding: 8px;border-style: solid;border-color: #a9a9a9;text-align:left;}
.tftable tr {background-color:#ffffff;}
.tftable td {font-size:12px;border-width: 1px;padding: 8px;border-style: solid;border-color: #a9a9a9;}
.tftable tr:hover {background-color:#F5F5F5;}
    .auto-style1 {
        width: 223px;
    }
</style>

</head>
<body style="overflow-x:hidden;margin-top:15px">
    <form id="form1" runat="server">


<table class="tftable" border="1" style="width:98%">
<tr><th class="auto-style1">Option</th><th>Current Project Settings</th><th></th></tr>
<tr><td class="auto-style1">QVW File</td><td><asp:Label ID="QVWFile" runat="server" Text=""></asp:Label></td> <td style="text-align:center"><asp:Image ID="QVWFileStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td> </tr>
<tr><td class="auto-style1">Project Name</td><td><asp:Label ID="ProjectName" runat="server" Text=""></asp:Label></td> <td style="text-align:center"><asp:Image ID="ProjectNameStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td> </tr>
<tr><td class="auto-style1">Project Description</td><td><asp:Label ID="ProjectDescription" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="ProjectDescriptionStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
<tr><td class="auto-style1">Project Thumbnail</td><td style="text-align:center"><asp:Image ID="Thumbnail" runat="server" Width="128px" Height="128px" /></td><td style="text-align:center"><asp:Image ID="ThumbnailStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
<tr><td class="auto-style1">Project User Manual</td><td><asp:HyperLink ID="UserManual" runat="server"></asp:HyperLink></td><td style="text-align:center"><asp:Image ID="UserManualStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
<%--<tr><td class="auto-style1">Publication Directory</td><td><asp:Label ID="PublicationDirectory" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="PublicationDirectoryStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>--%>
<%--<tr><td class="auto-style1">Add To Groups</td><td><asp:ListBox  ID="Groups" runat="server" Width="98%" Height="150px"></asp:ListBox></td><td style="text-align:center"><asp:Image ID="GroupsStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>--%>
<tr><td class="auto-style1">QVW Generated On</td><td><asp:Label ID="QVWGeneratedOn" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="Image7" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
<tr><td class="auto-style1">QVW Generated By</td><td><asp:Label ID="QVWGeneratedBy" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="Image8" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
<tr><td class="auto-style1">Report Reduction</td><td><asp:Label ID="LoopNReduce" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="Image11" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
<tr><td class="auto-style1">Server Last Updated by this Project on</td><td><asp:Label ID="ServerUpdatedOn" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="Image13" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
<tr><td class="auto-style1">Server Last Updated by </td><td><asp:Label ID="ServerUpdatedBy" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="Image14" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>

</table>
</form>
</body>
</html>
