//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 5/18/2016 1:56:19 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CdrContext
{

    [DatabaseAttribute(Name = "cdr_woh")]
    [ProviderAttribute(typeof(Devart.Data.PostgreSql.Linq.Provider.PgSqlDataProvider))]
    public partial class CdrDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(CdrDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertPatient(Patient instance);
        partial void UpdatePatient(Patient instance);
        partial void DeletePatient(Patient instance);
        partial void InsertOrganization(Organization instance);
        partial void UpdateOrganization(Organization instance);
        partial void DeleteOrganization(Organization instance);
        partial void InsertPatientIdentifier(PatientIdentifier instance);
        partial void UpdatePatientIdentifier(PatientIdentifier instance);
        partial void DeletePatientIdentifier(PatientIdentifier instance);
        partial void InsertPhysicalAddress(PhysicalAddress instance);
        partial void UpdatePhysicalAddress(PhysicalAddress instance);
        partial void DeletePhysicalAddress(PhysicalAddress instance);
        partial void InsertTelephoneNumber(TelephoneNumber instance);
        partial void UpdateTelephoneNumber(TelephoneNumber instance);
        partial void DeleteTelephoneNumber(TelephoneNumber instance);
        partial void InsertDataFeed(DataFeed instance);
        partial void UpdateDataFeed(DataFeed instance);
        partial void DeleteDataFeed(DataFeed instance);
        partial void InsertVisitEncounter(VisitEncounter instance);
        partial void UpdateVisitEncounter(VisitEncounter instance);
        partial void DeleteVisitEncounter(VisitEncounter instance);
        partial void InsertCharge(Charge instance);
        partial void UpdateCharge(Charge instance);
        partial void DeleteCharge(Charge instance);
        partial void InsertMeasurement(Measurement instance);
        partial void UpdateMeasurement(Measurement instance);
        partial void DeleteMeasurement(Measurement instance);
        partial void InsertMedication(Medication instance);
        partial void UpdateMedication(Medication instance);
        partial void DeleteMedication(Medication instance);
        partial void InsertImmunization(Immunization instance);
        partial void UpdateImmunization(Immunization instance);
        partial void DeleteImmunization(Immunization instance);
        partial void InsertInsuranceCoverage(InsuranceCoverage instance);
        partial void UpdateInsuranceCoverage(InsuranceCoverage instance);
        partial void DeleteInsuranceCoverage(InsuranceCoverage instance);
        partial void InsertDiagnosis(Diagnosis instance);
        partial void UpdateDiagnosis(Diagnosis instance);
        partial void DeleteDiagnosis(Diagnosis instance);
        partial void InsertProblem(Problem instance);
        partial void UpdateProblem(Problem instance);
        partial void DeleteProblem(Problem instance);
        partial void InsertAggregationLog(AggregationLog instance);
        partial void UpdateAggregationLog(AggregationLog instance);
        partial void DeleteAggregationLog(AggregationLog instance);

        #endregion

        public CdrDataContext() :
        base(GetConnectionString("CdrContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public CdrDataContext(MappingSource mappingSource) :
        base(GetConnectionString("CdrContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            System.Configuration.ConnectionStringSettings connectionStringSettings = System.Configuration.ConfigurationManager.ConnectionStrings[connectionStringName];
            if (connectionStringSettings == null)
                throw new InvalidOperationException("Connection string \"" + connectionStringName +"\" could not be found in the configuration file.");
            return connectionStringSettings.ConnectionString;
        }

        public CdrDataContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public CdrDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public CdrDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public CdrDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<Patient> Patients
        {
            get
            {
                return this.GetTable<Patient>();
            }
        }

        public Devart.Data.Linq.Table<Organization> Organizations
        {
            get
            {
                return this.GetTable<Organization>();
            }
        }

        public Devart.Data.Linq.Table<PatientIdentifier> PatientIdentifiers
        {
            get
            {
                return this.GetTable<PatientIdentifier>();
            }
        }

        public Devart.Data.Linq.Table<PhysicalAddress> PhysicalAddresses
        {
            get
            {
                return this.GetTable<PhysicalAddress>();
            }
        }

        public Devart.Data.Linq.Table<TelephoneNumber> TelephoneNumbers
        {
            get
            {
                return this.GetTable<TelephoneNumber>();
            }
        }

        public Devart.Data.Linq.Table<DataFeed> DataFeeds
        {
            get
            {
                return this.GetTable<DataFeed>();
            }
        }

        public Devart.Data.Linq.Table<VisitEncounter> VisitEncounters
        {
            get
            {
                return this.GetTable<VisitEncounter>();
            }
        }

        public Devart.Data.Linq.Table<Charge> Charges
        {
            get
            {
                return this.GetTable<Charge>();
            }
        }

        public Devart.Data.Linq.Table<Measurement> Measurements
        {
            get
            {
                return this.GetTable<Measurement>();
            }
        }

        public Devart.Data.Linq.Table<Medication> Medications
        {
            get
            {
                return this.GetTable<Medication>();
            }
        }

        public Devart.Data.Linq.Table<Immunization> Immunizations
        {
            get
            {
                return this.GetTable<Immunization>();
            }
        }

        public Devart.Data.Linq.Table<InsuranceCoverage> InsuranceCoverages
        {
            get
            {
                return this.GetTable<InsuranceCoverage>();
            }
        }

        public Devart.Data.Linq.Table<Diagnosis> Diagnoses
        {
            get
            {
                return this.GetTable<Diagnosis>();
            }
        }

        public Devart.Data.Linq.Table<Problem> Problems
        {
            get
            {
                return this.GetTable<Problem>();
            }
        }

        public Devart.Data.Linq.Table<AggregationLog> AggregationLogs
        {
            get
            {
                return this.GetTable<AggregationLog>();
            }
        }
    }
}
