using FileProcessor;
using System;
using System.Collections.Generic;
using System.Configuration;

namespace ReportFileGenerator
{
    public class GenerateReportFile : BaseFileProcessor
    {
        public GenerateReportFile() {  }

        public static void ExecuteReportFileGenerate(string args)
        {
            try
            {
                Process();
            }
            catch (Exception ex)
            {
                BaseFileProcessor.LogError(ex, "ExecutePasswordResetUtility || An exception occured during the processing." + args, true);
            }
        }
        private static void Process()
        {
            try
            {
                //set the begin and end date
                DateTime? startDateValue = DateTime.Parse(GetConfigStartDateRange());
                DateTime? endDateValue = DateTime.Parse(GetConfigEndDateDateRange());

                // set report type [Group, Report, User]//do we need to generate report by group, user or report name
                var reportTypeValue = GetReportTypeCategory();
                var reportTypeEnum = ParseEnum<Enumerations.eReportType>(reportTypeValue); // (Enumerations.eReportType)Enum.Parse(typeof(Enumerations.eReportType), value.ToString(), true); 

                //set output file type //CSV, Excel or Txt
                var outPutFileTypeValue = GetOutPutFileFormat();
                var outPutFileTypeEnum = ParseEnum<Enumerations.eOutputType>(outPutFileTypeValue);

                //get what log file type to generate //do we need to generate the iislog, session log or audit log
                var logTypeList = GetLogTypeList();
                foreach (var log in logTypeList)
                {
                    var logType = ParseEnum<Enumerations.eLogType>(log);

                    if (logType == Enumerations.eLogType.iIS)
                        GenerateIisLogsReport.GenerateReport(startDateValue, endDateValue, reportTypeEnum.ToString(), outPutFileTypeEnum.ToString(),"","");

                    if (logType == Enumerations.eLogType.Audit)
                        GenerateQVAuditLogsReport.GenerateReport(startDateValue, endDateValue,  reportTypeEnum.ToString(), outPutFileTypeEnum.ToString(), "", "");

                    if (logType == Enumerations.eLogType.Session)
                        GenerateQVSessionLogsReport.GenerateReport(startDateValue, endDateValue,  reportTypeEnum.ToString(), outPutFileTypeEnum.ToString(), "", "");
                }
            }
            catch (Exception ex)
            {
                BaseFileProcessor.LogError(ex, "GenerateReportFile:Process", true);
            }
        }
                
        #region Utility

        public static T ParseEnum<T>(string value)
        {
            return (T)Enum.Parse(typeof(T), value, true);
        }

        #endregion
        #region Configurations Settings
        private static string GetOutPutFileFormat()
        {
            // For Example - D:\Projects\SomeProject\SomeFolder
            return (ConfigurationManager.AppSettings != null &&
                    ConfigurationManager.AppSettings["OutPutFileFormat"] != null) ?
                    ConfigurationManager.AppSettings["OutPutFileFormat"].ToString() :
                    string.Empty;
        }

        /// <summary>
        /// returns the type of report to be generated by [group,user,report]
        /// </summary>
        /// <returns></returns>
        private static string GetReportTypeCategory()
        {
            // For Example - D:\Projects\SomeProject\SomeFolder
            return (ConfigurationManager.AppSettings != null &&
                    ConfigurationManager.AppSettings["ReportTypeCategory"] != null) ?
                    ConfigurationManager.AppSettings["ReportTypeCategory"].ToString() :
                    string.Empty;
        }
        private static string GetConfigStartDateRange()
        {
            // For Example - D:\Projects\SomeProject\SomeFolder
            return (ConfigurationManager.AppSettings != null &&
                    ConfigurationManager.AppSettings["StartDate"] != null) ?
                    ConfigurationManager.AppSettings["StartDate"].ToString() :
                    string.Empty;
        }

        private static string GetConfigEndDateDateRange()
        {
            // For Example - D:\Projects\SomeProject\SomeFolder
            return (ConfigurationManager.AppSettings != null &&
                    ConfigurationManager.AppSettings["EndDate"] != null) ?
                    ConfigurationManager.AppSettings["EndDate"].ToString() :
                    string.Empty;
        }

        /// <summary>
        /// returns list of the LogTypeCategory for log files
        /// </summary>
        /// <returns></returns>
        private static List<string> GetLogTypeList()
        {
            // For Example - D:\Projects\SomeProject\SomeFolder
            var listLogTypeCategory = new List<string>();
            if (ConfigurationManager.AppSettings != null && ConfigurationManager.AppSettings["LogType"] != null)
            {
                listLogTypeCategory = new List<string>(ConfigurationManager.AppSettings["LogType"].Split(new char[] { ',' }));
            }
            
            return listLogTypeCategory;
        }

        #endregion
    }
}
