//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 3/22/2016 2:24:04 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CLSdbContext
{

    /// <summary>
    /// This table holds information on the Medicare reimbursement rates for each test by locality
    /// </summary>
    [Table(Name = @"""ReimbursementRates""")]
    public partial class ReimbursementRate : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private System.Nullable<int> _FkCodeId;

        private System.Nullable<int> _Year;

        private System.Nullable<double> _Rate;

        private System.Nullable<int> _FkLocalityId;
        #pragma warning restore 0649

        private EntityRef<Code> _Code;

        private EntityRef<Locality> _Locality;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnFkCodeIdChanging(System.Nullable<int> value);
        partial void OnFkCodeIdChanged();
        partial void OnYearChanging(System.Nullable<int> value);
        partial void OnYearChanged();
        partial void OnRateChanging(System.Nullable<double> value);
        partial void OnRateChanged();
        partial void OnFkLocalityIdChanging(System.Nullable<int> value);
        partial void OnFkLocalityIdChanged();
        #endregion

        public ReimbursementRate()
        {
            this._Code  = default(EntityRef<Code>);
            this._Locality  = default(EntityRef<Locality>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"""Id""", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "serial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for FkCodeId in the schema.
        /// </summary>
        [Column(Name = @"""FkCodeId""", Storage = "_FkCodeId", DbType = "int4", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> FkCodeId
        {
            get
            {
                return this._FkCodeId;
            }
            set
            {
                if (this._FkCodeId != value)
                {
                    if (this._Code.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnFkCodeIdChanging(value);
                    this.SendPropertyChanging();
                    this._FkCodeId = value;
                    this.SendPropertyChanged("FkCodeId");
                    this.OnFkCodeIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Year in the schema.
        /// </summary>
        [Column(Name = @"""Year""", Storage = "_Year", DbType = "int4", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                if (this._Year != value)
                {
                    this.OnYearChanging(value);
                    this.SendPropertyChanging();
                    this._Year = value;
                    this.SendPropertyChanged("Year");
                    this.OnYearChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Rate in the schema.
        /// </summary>
        [Column(Name = @"""Rate""", Storage = "_Rate", DbType = "double precision", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<double> Rate
        {
            get
            {
                return this._Rate;
            }
            set
            {
                if (this._Rate != value)
                {
                    this.OnRateChanging(value);
                    this.SendPropertyChanging();
                    this._Rate = value;
                    this.SendPropertyChanged("Rate");
                    this.OnRateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for FkLocalityId in the schema.
        /// </summary>
        [Column(Name = @"""FkLocalityId""", Storage = "_FkLocalityId", DbType = "int4", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> FkLocalityId
        {
            get
            {
                return this._FkLocalityId;
            }
            set
            {
                if (this._FkLocalityId != value)
                {
                    if (this._Locality.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnFkLocalityIdChanging(value);
                    this.SendPropertyChanging();
                    this._FkLocalityId = value;
                    this.SendPropertyChanged("FkLocalityId");
                    this.OnFkLocalityIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Code in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Code_ReimbursementRate", Storage="_Code", ThisKey="FkCodeId", OtherKey="Id", IsForeignKey=true)]
        public Code Code
        {
            get
            {
                return this._Code.Entity;
            }
            set
            {
                Code previousValue = this._Code.Entity;
                if ((previousValue != value) || (this._Code.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Code.Entity = null;
                        previousValue.ReimbursementRates.Remove(this);
                    }
                    this._Code.Entity = value;
                    if (value != null)
                    {
                        this._FkCodeId = value.Id;
                        value.ReimbursementRates.Add(this);
                    }
                    else
                    {
                        this._FkCodeId = default(System.Nullable<int>);
                    }
                    this.SendPropertyChanged("Code");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Locality in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Locality_ReimbursementRate", Storage="_Locality", ThisKey="FkLocalityId", OtherKey="Id", IsForeignKey=true)]
        public Locality Locality
        {
            get
            {
                return this._Locality.Entity;
            }
            set
            {
                Locality previousValue = this._Locality.Entity;
                if ((previousValue != value) || (this._Locality.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Locality.Entity = null;
                        previousValue.ReimbursementRates.Remove(this);
                    }
                    this._Locality.Entity = value;
                    if (value != null)
                    {
                        this._FkLocalityId = value.Id;
                        value.ReimbursementRates.Add(this);
                    }
                    else
                    {
                        this._FkLocalityId = default(System.Nullable<int>);
                    }
                    this.SendPropertyChanged("Locality");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
