//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 3/22/2016 2:24:04 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CLSdbContext
{

    /// <summary>
    /// This table holds information on the Roche Localities
    /// </summary>
    [Table(Name = @"""Localities""")]
    public partial class Locality : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _Locality1;

        private string _LocalityDescription;
        #pragma warning restore 0649

        private EntitySet<ReimbursementRate> _ReimbursementRates;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnLocality1Changing(string value);
        partial void OnLocality1Changed();
        partial void OnLocalityDescriptionChanging(string value);
        partial void OnLocalityDescriptionChanged();
        #endregion

        public Locality()
        {
            this._ReimbursementRates = new EntitySet<ReimbursementRate>(new Action<ReimbursementRate>(this.attach_ReimbursementRates), new Action<ReimbursementRate>(this.detach_ReimbursementRates));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"""Id""", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "serial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Locality1 in the schema.
        /// </summary>
        [Column(Name = @"""Locality1""", Storage = "_Locality1", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string Locality1
        {
            get
            {
                return this._Locality1;
            }
            set
            {
                if (this._Locality1 != value)
                {
                    this.OnLocality1Changing(value);
                    this.SendPropertyChanging();
                    this._Locality1 = value;
                    this.SendPropertyChanged("Locality1");
                    this.OnLocality1Changed();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for LocalityDescription in the schema.
        /// </summary>
        [Column(Name = @"""LocalityDescription""", Storage = "_LocalityDescription", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string LocalityDescription
        {
            get
            {
                return this._LocalityDescription;
            }
            set
            {
                if (this._LocalityDescription != value)
                {
                    this.OnLocalityDescriptionChanging(value);
                    this.SendPropertyChanging();
                    this._LocalityDescription = value;
                    this.SendPropertyChanged("LocalityDescription");
                    this.OnLocalityDescriptionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ReimbursementRates in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Locality_ReimbursementRate", Storage="_ReimbursementRates", ThisKey="Id", OtherKey="FkLocalityId", DeleteRule="NO ACTION")]
        public EntitySet<ReimbursementRate> ReimbursementRates
        {
            get
            {
                return this._ReimbursementRates;
            }
            set
            {
                this._ReimbursementRates.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_ReimbursementRates(ReimbursementRate entity)
        {
            this.SendPropertyChanging("ReimbursementRates");
            entity.Locality = this;
        }
    
        private void detach_ReimbursementRates(ReimbursementRate entity)
        {
            this.SendPropertyChanging("ReimbursementRates");
            entity.Locality = null;
        }
    }

}
