//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 4/13/2016 4:22:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace RedoxCacheDbContext
{

    [DatabaseAttribute(Name = "redoxcache")]
    [ProviderAttribute(typeof(Devart.Data.PostgreSql.Linq.Provider.PgSqlDataProvider))]
    public partial class RedoxCacheContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(RedoxCacheContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertScheduling(Scheduling instance);
        partial void UpdateScheduling(Scheduling instance);
        partial void DeleteScheduling(Scheduling instance);
        partial void InsertSourceFeed(SourceFeed instance);
        partial void UpdateSourceFeed(SourceFeed instance);
        partial void DeleteSourceFeed(SourceFeed instance);

        #endregion

        public RedoxCacheContext() :
        base(GetConnectionString("RedoxCacheContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public RedoxCacheContext(MappingSource mappingSource) :
        base(GetConnectionString("RedoxCacheContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            System.Configuration.ConnectionStringSettings connectionStringSettings = System.Configuration.ConfigurationManager.ConnectionStrings[connectionStringName];
            if (connectionStringSettings == null)
                throw new InvalidOperationException("Connection string \"" + connectionStringName +"\" could not be found in the configuration file.");
            return connectionStringSettings.ConnectionString;
        }

        public RedoxCacheContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public RedoxCacheContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public RedoxCacheContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public RedoxCacheContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<Scheduling> Schedulings
        {
            get
            {
                return this.GetTable<Scheduling>();
            }
        }

        public Devart.Data.Linq.Table<SourceFeed> SourceFeeds
        {
            get
            {
                return this.GetTable<SourceFeed>();
            }
        }
    }
}
