//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 4/5/2016 9:50:51 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace RedoxCacheDbContext
{

    /// <summary>
    /// There are no comments for RedoxCacheDbContext.SourceFeed in the schema.
    /// </summary>
    [Table(Name = @"public.sourcefeed")]
    public partial class SourceFeed : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private string _FacilityCode;
        #pragma warning restore 0649

        private EntitySet<Scheduling> _Schedulings;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnFacilityCodeChanging(string value);
        partial void OnFacilityCodeChanged();
        #endregion

        public SourceFeed()
        {
            this._Schedulings = new EntitySet<Scheduling>(new Action<Scheduling>(this.attach_Schedulings), new Action<Scheduling>(this.detach_Schedulings));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for FacilityCode in the schema.
        /// </summary>
        [Column(Name = @"facilitycode", Storage = "_FacilityCode", CanBeNull = false, DbType = "varchar", IsPrimaryKey = true)]
        public string FacilityCode
        {
            get
            {
                return this._FacilityCode;
            }
        }

    
        /// <summary>
        /// There are no comments for Schedulings in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="SourceFeed_Scheduling", Storage="_Schedulings", ThisKey="FacilityCode", OtherKey="FacilityCode")]
        public EntitySet<Scheduling> Schedulings
        {
            get
            {
                return this._Schedulings;
            }
            set
            {
                this._Schedulings.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Schedulings(Scheduling entity)
        {
            this.SendPropertyChanging("Schedulings");
            entity.SourceFeed = this;
        }
    
        private void detach_Schedulings(Scheduling entity)
        {
            this.SendPropertyChanging("Schedulings");
            entity.SourceFeed = null;
        }
    }

}
