//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 4/13/2016 4:22:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace RedoxCacheDbContext
{

    /// <summary>
    /// There are no comments for RedoxCacheDbContext.SourceFeed in the schema.
    /// </summary>
    [Table(Name = @"public.sourcefeed")]
    public partial class SourceFeed : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private System.Guid _SourceId;

        private string _SourceName;

        private System.Guid _QueryDestinationId;

        private string _QueryDestinationName;

        private string _BestIdType;
        #pragma warning restore 0649

        private EntitySet<Scheduling> _Schedulings;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnSourceIdChanging(System.Guid value);
        partial void OnSourceIdChanged();
        partial void OnSourceNameChanging(string value);
        partial void OnSourceNameChanged();
        partial void OnQueryDestinationIdChanging(System.Guid value);
        partial void OnQueryDestinationIdChanged();
        partial void OnQueryDestinationNameChanging(string value);
        partial void OnQueryDestinationNameChanged();
        partial void OnBestIdTypeChanging(string value);
        partial void OnBestIdTypeChanged();
        #endregion

        public SourceFeed()
        {
            this._Schedulings = new EntitySet<Scheduling>(new Action<Scheduling>(this.attach_Schedulings), new Action<Scheduling>(this.detach_Schedulings));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for SourceId in the schema.
        /// </summary>
        [Column(Name = @"sourceid", Storage = "_SourceId", CanBeNull = false, DbType = "uuid NOT NULL", IsPrimaryKey = true)]
        public System.Guid SourceId
        {
            get
            {
                return this._SourceId;
            }
            set
            {
                if (this._SourceId != value)
                {
                    this.OnSourceIdChanging(value);
                    this.SendPropertyChanging();
                    this._SourceId = value;
                    this.SendPropertyChanged("SourceId");
                    this.OnSourceIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for SourceName in the schema.
        /// </summary>
        [Column(Name = @"sourcename", Storage = "_SourceName", CanBeNull = false, DbType = "varchar NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string SourceName
        {
            get
            {
                return this._SourceName;
            }
            set
            {
                if (this._SourceName != value)
                {
                    this.OnSourceNameChanging(value);
                    this.SendPropertyChanging();
                    this._SourceName = value;
                    this.SendPropertyChanged("SourceName");
                    this.OnSourceNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for QueryDestinationId in the schema.
        /// </summary>
        [Column(Name = @"querydestinationid", Storage = "_QueryDestinationId", CanBeNull = false, DbType = "uuid NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Guid QueryDestinationId
        {
            get
            {
                return this._QueryDestinationId;
            }
            set
            {
                if (this._QueryDestinationId != value)
                {
                    this.OnQueryDestinationIdChanging(value);
                    this.SendPropertyChanging();
                    this._QueryDestinationId = value;
                    this.SendPropertyChanged("QueryDestinationId");
                    this.OnQueryDestinationIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for QueryDestinationName in the schema.
        /// </summary>
        [Column(Name = @"querydestinationname", Storage = "_QueryDestinationName", CanBeNull = false, DbType = "varchar NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string QueryDestinationName
        {
            get
            {
                return this._QueryDestinationName;
            }
            set
            {
                if (this._QueryDestinationName != value)
                {
                    this.OnQueryDestinationNameChanging(value);
                    this.SendPropertyChanging();
                    this._QueryDestinationName = value;
                    this.SendPropertyChanged("QueryDestinationName");
                    this.OnQueryDestinationNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BestIdType in the schema.
        /// </summary>
        [Column(Name = @"bestidtype", Storage = "_BestIdType", CanBeNull = false, DbType = "varchar NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string BestIdType
        {
            get
            {
                return this._BestIdType;
            }
            set
            {
                if (this._BestIdType != value)
                {
                    this.OnBestIdTypeChanging(value);
                    this.SendPropertyChanging();
                    this._BestIdType = value;
                    this.SendPropertyChanged("BestIdType");
                    this.OnBestIdTypeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Schedulings in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="SourceFeed_Scheduling", Storage="_Schedulings", ThisKey="SourceId", OtherKey="SourceFeedId")]
        public EntitySet<Scheduling> Schedulings
        {
            get
            {
                return this._Schedulings;
            }
            set
            {
                this._Schedulings.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Schedulings(Scheduling entity)
        {
            this.SendPropertyChanging("Schedulings");
            entity.SourceFeed = this;
        }
    
        private void detach_Schedulings(Scheduling entity)
        {
            this.SendPropertyChanging("Schedulings");
            entity.SourceFeed = null;
        }
    }

}
