//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 4/5/2016 9:50:51 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace RedoxCacheDbContext
{

    /// <summary>
    /// There are no comments for RedoxCacheDbContext.Scheduling in the schema.
    /// </summary>
    [Table(Name = @"public.scheduling")]
    public partial class Scheduling : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _dbid;

        private long _TransmissionId;

        private string _FacilityCode;

        private string _Content;
        #pragma warning restore 0649

        private EntityRef<SourceFeed> _SourceFeed;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OndbidChanging(long value);
        partial void OndbidChanged();
        partial void OnTransmissionIdChanging(long value);
        partial void OnTransmissionIdChanged();
        partial void OnFacilityCodeChanging(string value);
        partial void OnFacilityCodeChanged();
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        #endregion

        public Scheduling()
        {
            this._SourceFeed  = default(EntityRef<SourceFeed>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for dbid in the schema.
        /// </summary>
        [Column(Storage = "_dbid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "bigserial NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public long dbid
        {
            get
            {
                return this._dbid;
            }
        }

    
        /// <summary>
        /// There are no comments for TransmissionId in the schema.
        /// </summary>
        [Column(Name = @"transmissionid", Storage = "_TransmissionId", CanBeNull = false, DbType = "int8 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long TransmissionId
        {
            get
            {
                return this._TransmissionId;
            }
            set
            {
                if (this._TransmissionId != value)
                {
                    this.OnTransmissionIdChanging(value);
                    this.SendPropertyChanging();
                    this._TransmissionId = value;
                    this.SendPropertyChanged("TransmissionId");
                    this.OnTransmissionIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for FacilityCode in the schema.
        /// </summary>
        [Column(Name = @"facilitycode", Storage = "_FacilityCode", DbType = "varchar", UpdateCheck = UpdateCheck.Never)]
        public string FacilityCode
        {
            get
            {
                return this._FacilityCode;
            }
            set
            {
                if (this._FacilityCode != value)
                {
                    if (this._SourceFeed.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnFacilityCodeChanging(value);
                    this.SendPropertyChanging();
                    this._FacilityCode = value;
                    this.SendPropertyChanged("FacilityCode");
                    this.OnFacilityCodeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Content in the schema.
        /// </summary>
        [Column(Name = @"content", Storage = "_Content", CanBeNull = false, DbType = "varchar NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                if (this._Content != value)
                {
                    this.OnContentChanging(value);
                    this.SendPropertyChanging();
                    this._Content = value;
                    this.SendPropertyChanged("Content");
                    this.OnContentChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for SourceFeed in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="SourceFeed_Scheduling", Storage="_SourceFeed", ThisKey="FacilityCode", OtherKey="FacilityCode", IsForeignKey=true)]
        public SourceFeed SourceFeed
        {
            get
            {
                return this._SourceFeed.Entity;
            }
            set
            {
                SourceFeed previousValue = this._SourceFeed.Entity;
                if ((previousValue != value) || (this._SourceFeed.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._SourceFeed.Entity = null;
                        previousValue.Schedulings.Remove(this);
                    }
                    this._SourceFeed.Entity = value;
                    if (value != null)
                    {
                        this._FacilityCode = value.FacilityCode;
                        value.Schedulings.Add(this);
                    }
                    else
                    {
                        this._FacilityCode = default(string);
                    }
                    this.SendPropertyChanged("SourceFeed");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
