//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 3/22/2016 1:37:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;
using ConfigIt;

namespace CLSdbContext
{    
    [ProviderAttribute(typeof(Devart.Data.PostgreSql.Linq.Provider.PgSqlDataProvider))]
    public partial class CLSdbDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(CLSdbDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertFootnote(Footnote instance);
        partial void UpdateFootnote(Footnote instance);
        partial void DeleteFootnote(Footnote instance);
        partial void InsertWeburl(Weburl instance);
        partial void UpdateWeburl(Weburl instance);
        partial void DeleteWeburl(Weburl instance);
        partial void InsertCode(Code instance);
        partial void UpdateCode(Code instance);
        partial void DeleteCode(Code instance);
        partial void InsertAnalyzer(Analyzer instance);
        partial void UpdateAnalyzer(Analyzer instance);
        partial void DeleteAnalyzer(Analyzer instance);
        partial void InsertLocality(Locality instance);
        partial void UpdateLocality(Locality instance);
        partial void DeleteLocality(Locality instance);
        partial void InsertReimbursementRate(ReimbursementRate instance);
        partial void UpdateReimbursementRate(ReimbursementRate instance);
        partial void DeleteReimbursementRate(ReimbursementRate instance);
        partial void InsertSearchTerm(SearchTerm instance);
        partial void UpdateSearchTerm(SearchTerm instance);
        partial void DeleteSearchTerm(SearchTerm instance);

        #endregion

        public CLSdbDataContext() :
        base(GetConnectionString("CLSdbDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public CLSdbDataContext(MappingSource mappingSource) :
        base(GetConnectionString("CLSdbDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            var connectionStringSettings = "";
            try
            {
                var databaseName = "CLSdbDataContextConnectionString";
                //var connectionStringSettings = ConfigurationManager.ConnectionStrings[connectionStringName].ConnectionString;
                 connectionStringSettings = (EnvironmentSettings.ConnectionStrings[databaseName].ConnectionString);
                if (connectionStringSettings == null)
                    throw new InvalidOperationException("Connection string \"" + connectionStringName + "\" could not be found in the configuration file.");
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException(connectionStringSettings + "could not connext");
            }            
            return connectionStringSettings;
        }

        public CLSdbDataContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public CLSdbDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public CLSdbDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public CLSdbDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<Footnote> Footnotes
        {
            get
            {
                return this.GetTable<Footnote>();
            }
        }

        public Devart.Data.Linq.Table<Weburl> Weburls
        {
            get
            {
                return this.GetTable<Weburl>();
            }
        }

        public Devart.Data.Linq.Table<Code> Codes
        {
            get
            {
                return this.GetTable<Code>();
            }
        }

        public Devart.Data.Linq.Table<Analyzer> Analyzers
        {
            get
            {
                return this.GetTable<Analyzer>();
            }
        }

        public Devart.Data.Linq.Table<Locality> Localities
        {
            get
            {
                return this.GetTable<Locality>();
            }
        }

        public Devart.Data.Linq.Table<ReimbursementRate> ReimbursementRates
        {
            get
            {
                return this.GetTable<ReimbursementRate>();
            }
        }

        public Devart.Data.Linq.Table<SearchTerm> SearchTerms
        {
            get
            {
                return this.GetTable<SearchTerm>();
            }
        }
    }
}
