<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Diff.aspx.cs" Inherits="MillimanProjectManConsole.Admin.Diff" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
 <style type="text/css">
    .tftable {font-size:12px;color:#333333;width:100%;border-width: 1px;border-color: #a9a9a9;border-collapse: collapse;width:580px}
    .tftable th {font-size:12px;background-color:#F5F5F5;border-width: 1px;padding: 8px;border-style: solid;border-color: #a9a9a9;text-align:left;}
    .tftable tr {background-color:#ffffff;}
    .tftable td {font-size:12px;border-width: 1px;padding: 8px;border-style: solid;border-color: #a9a9a9;}
    .tftable tr:hover {background-color:#F5F5F5;}
        .auto-style1 {
            width: 223px;
        }
</style>
</head>
<body style="overflow-x:hidden;margin-top:15px">
    <form id="form1" runat="server">
    <table class="tftable" border="1">
        <tr><th class="auto-style1">Option</th><th>Local</th><th>Server</th><th></th></tr>
        <tr><td class="auto-style1">QVW File</td><td><asp:Label ID="LocalQVWFile" runat="server" Text=""></asp:Label></td><td><asp:Label ID="ServerQVWFile" runat="server" Text=""></asp:Label></td> <td style="text-align:center"><asp:Image ID="QVWFileStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td> </tr>
        <tr><td class="auto-style1">Project Name</td><td><asp:Label ID="LocalProjectName" runat="server" Text=""></asp:Label></td><td><asp:Label ID="ServerProjectName" runat="server" Text=""></asp:Label></td> <td style="text-align:center"><asp:Image ID="ProjectNameStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td> </tr>
        <tr><td class="auto-style1">Project Description</td><td><asp:Label ID="LocalProjectDescription" runat="server" Text=""/></td><td><asp:Label ID="ServerProjectDescription" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="ProjectDescriptionStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
        <tr><td class="auto-style1">Project Thumbnail</td><td style="text-align:center"><asp:Image ID="LocalThumbnail" runat="server" Width="128px" Height="128px" /></td><td style="text-align:center"><asp:Image ID="ServerThumbnail" runat="server" Width="128px" Height="128px" /></td><td style="text-align:center"><asp:Image ID="ThumbnailStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
        <tr><td class="auto-style1">Project User Manual</td><td><asp:HyperLink ID="LocalUserManual" runat="server"></asp:HyperLink></td><td><asp:HyperLink ID="ServerUserManual" runat="server"></asp:HyperLink></td><td style="text-align:center"><asp:Image ID="UserManualStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
        <tr><td class="auto-style1">Publication Directory</td><td><asp:Label ID="LocalPublicationDirectory" runat="server" Text=""/></td><td><asp:Label ID="ServerPublicationDirectory" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="PublicationDirectoryStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
        <tr><td class="auto-style1">Add To Groups</td><td><asp:ListBox  ID="LocalGroups" runat="server" Width="98%" Height="150px"></asp:ListBox></td><td><asp:ListBox  ID="ServerGroups" runat="server" Width="98%" Height="150px"></asp:ListBox></td><td style="text-align:center"><asp:Image ID="GroupsStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
        <tr><td class="auto-style1">QVW Generated On</td><td><asp:Label ID="LocalQVWGeneratedOn" runat="server" Text=""/></td><td><asp:Label ID="ServerQVWGeneratedOn" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="QVWGeneratedOnStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
        <tr><td class="auto-style1">QVW Generated By</td><td><asp:Label ID="LocalQVWGeneratedBy" runat="server" Text=""/></td><td><asp:Label ID="ServerQVWGeneratedBy" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="QVWGeneratedByStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
        <tr style="visibility:collapse"><td class="auto-style1">Loop&Reduce</td><td><asp:Label ID="LocalLoopNReduce" runat="server" Text=""/></td><td><asp:Label ID="ServerLoopNReduce" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="LoopNReduceStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
        <tr><td class="auto-style1">Server Last Updated by this Project on</td><td><asp:Label ID="LocalServerUpdatedOn" runat="server" Text=""/></td><td><asp:Label ID="ServerServerUpdatedOn" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="ServerUpdatedOnStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
        <tr><td class="auto-style1">Server Last Updated by </td><td><asp:Label ID="LocalServerUpdatedBy" runat="server" Text=""/></td><td><asp:Label ID="ServerServerUpdatedBy" runat="server" Text=""/></td><td style="text-align:center"><asp:Image ID="ServerUpdatedByStatus" runat="server" ImageUrl="~/images/OK-icon.png" /></td></tr>
     </table>
     </form>
</body>
</html>
