//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 3/22/2016 1:37:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CLSdbContext
{

    /// <summary>
    /// This table holds the url of the CMS website where this data is available
    /// </summary>
    [Table(Name = @"weburl")]
    public partial class Weburl : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _Displaytext;

        private string _Webaddressurl;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnDisplaytextChanging(string value);
        partial void OnDisplaytextChanged();
        partial void OnWebaddressurlChanging(string value);
        partial void OnWebaddressurlChanged();
        #endregion

        public Weburl()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "SERIAL NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Displaytext in the schema.
        /// </summary>
        [Column(Name = @"displaytext", Storage = "_Displaytext", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Displaytext
        {
            get
            {
                return this._Displaytext;
            }
            set
            {
                if (this._Displaytext != value)
                {
                    this.OnDisplaytextChanging(value);
                    this.SendPropertyChanging();
                    this._Displaytext = value;
                    this.SendPropertyChanged("Displaytext");
                    this.OnDisplaytextChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Webaddressurl in the schema.
        /// </summary>
        [Column(Name = @"webaddressurl", Storage = "_Webaddressurl", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Webaddressurl
        {
            get
            {
                return this._Webaddressurl;
            }
            set
            {
                if (this._Webaddressurl != value)
                {
                    this.OnWebaddressurlChanging(value);
                    this.SendPropertyChanging();
                    this._Webaddressurl = value;
                    this.SendPropertyChanged("Webaddressurl");
                    this.OnWebaddressurlChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
