//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 2/22/2016 6:20:08 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace CLSdbContext
{

    /// <summary>
    /// This table holds information on which tests are available for a given analyzer
    /// </summary>
    [Table(Name = @"rmrrdb_20160222.analyzers")]
    public partial class Analyzer : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _AnalyzerName;

        private string _Notes;

        private System.Nullable<int> _FkCodeId;
        #pragma warning restore 0649

        private EntityRef<Code> _Code;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnAnalyzerNameChanging(string value);
        partial void OnAnalyzerNameChanged();
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        partial void OnFkCodeIdChanging(System.Nullable<int> value);
        partial void OnFkCodeIdChanged();
        #endregion

        public Analyzer()
        {
            this._Code  = default(EntityRef<Code>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "SERIAL NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for AnalyzerName in the schema.
        /// </summary>
        [Column(Name = @"analyzer_name", Storage = "_AnalyzerName", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string AnalyzerName
        {
            get
            {
                return this._AnalyzerName;
            }
            set
            {
                if (this._AnalyzerName != value)
                {
                    this.OnAnalyzerNameChanging(value);
                    this.SendPropertyChanging();
                    this._AnalyzerName = value;
                    this.SendPropertyChanged("AnalyzerName");
                    this.OnAnalyzerNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Notes in the schema.
        /// </summary>
        [Column(Name = @"notes", Storage = "_Notes", DbType = "VARCHAR", UpdateCheck = UpdateCheck.Never)]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                if (this._Notes != value)
                {
                    this.OnNotesChanging(value);
                    this.SendPropertyChanging();
                    this._Notes = value;
                    this.SendPropertyChanged("Notes");
                    this.OnNotesChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for FkCodeId in the schema.
        /// </summary>
        [Column(Name = @"fk_code_id", Storage = "_FkCodeId", DbType = "INT4", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> FkCodeId
        {
            get
            {
                return this._FkCodeId;
            }
            set
            {
                if (this._FkCodeId != value)
                {
                    if (this._Code.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnFkCodeIdChanging(value);
                    this.SendPropertyChanging();
                    this._FkCodeId = value;
                    this.SendPropertyChanged("FkCodeId");
                    this.OnFkCodeIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Code in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Code_Analyzer", Storage="_Code", ThisKey="FkCodeId", OtherKey="Id", IsForeignKey=true)]
        public Code Code
        {
            get
            {
                return this._Code.Entity;
            }
            set
            {
                Code previousValue = this._Code.Entity;
                if ((previousValue != value) || (this._Code.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Code.Entity = null;
                        previousValue.Analyzers.Remove(this);
                    }
                    this._Code.Entity = value;
                    if (value != null)
                    {
                        this._FkCodeId = value.Id;
                        value.Analyzers.Add(this);
                    }
                    else
                    {
                        this._FkCodeId = default(System.Nullable<int>);
                    }
                    this.SendPropertyChanged("Code");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
