using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Milliman.Common {
    /// <summary>
    /// Represents the reduction criteria along with the QVW name to reduce
    /// </summary>
    public class ReductionSettings {
        private string _ReducedQVWName;

        /// <summary>)
        /// INPUT:Name of the QVW once reduced - should not contain the path but be in same directory as reduce.config file(s). 
        /// (callers responsability to ensure unique )
        /// </summary>
        public string ReducedQVWName {
            get { return _ReducedQVWName; }
            set { _ReducedQVWName = value; }
        }

        private string _QVWStatusLog;

        /// <summary>
        /// INPUT:Name of log file generated by reduction process ( callers responsabilty to make unique )
        /// </summary>
        public string QVWStatusLog {
            get { return _QVWStatusLog; }
            set { _QVWStatusLog = value; }
        }

        private List<string> _IgnoreTables;

        /// <summary>
        /// INPUT:Instructs the hierarchy procesor to exclude specific tables by name - case sensitive
        /// </summary>
        public List<string> IgnoreTables {
            get { return _IgnoreTables; }
            set {
                if (value == null)
                    _IgnoreTables = new List<string>();
                else
                  _IgnoreTables = value; }
        }

        private List<string> _DropTables;

        /// <summary>
        /// INPUT:Instructs the system to ensure the listed tables have been dropped in reduced QVW - case sensitive
        /// </summary>
        public List<string> DropTables {
            get { return _DropTables; }
            set {
                if (value == null)
                    _DropTables = new List<string>();
                else
                    _DropTables = value; }
        }

        private bool _DropDisassociatedDataModelTables;

        /// <summary>
        /// INPUT:When set to true, if the input selected values do not contain a selection from a table that is part of the
        /// hierarchy, the table as referenced by the hierarchy should be dropped - prevents ePHI leaks in disassociated tables
        /// </summary>
        public bool DropDisassociatedDataModelTables {
            get { return _DropDisassociatedDataModelTables; }
            set { _DropDisassociatedDataModelTables = value; }
        }


        private List<NVPair> _SelectionCriteria;

        /// <summary>
        /// INPUT:A list of data model field names and values to select for reduction
        /// </summary>
        public List<NVPair> SelectionCriteria {
            get { return _SelectionCriteria; }
            set {
                if (value == null)
                    _SelectionCriteria = new List<NVPair>();
                else
                    _SelectionCriteria = value; }
        }

        private string _HierarchyFile;
        /// <summary>
        /// INPUT:if populated, save a hierarchy file to name provided ( caller must ensure unique )
        /// </summary>
        public string HierarchyFile {
            get { return _HierarchyFile; }
            set { _HierarchyFile = value; }
        }

        private string _MapFile;
        /// <summary>
        /// INPUT:if populated, save a map file to name provided ( caller must ensure unique )
        /// </summary>
        public string MapFile {
            get { return _MapFile; }
            set { _MapFile = value; }
        }

        private string _ConceptFile;
        /// <summary>
        /// INPUT:if populated, save a concept file to name provided ( caller must ensure unique )
        /// </summary>
        public string ConceptFile {
            get { return _ConceptFile; }
            set { _ConceptFile = value; }
        }

        /// <summary>
        /// for each NVPair item,  look up the column name (FieldName) in the data created
        /// from partial reload on MASTER QVW, and for all the items in that column create a list of all
        /// the unique values in that column - write output back to (Value) field specified file
        /// items in list should be tilde delimited '~'.  
        /// </summary>
        private List<NVPair> _UniqueValuesFromMasterQVWColumns;

        public List<NVPair> UniqueValuesFromMasterQVWColumns {
            get { return _UniqueValuesFromMasterQVWColumns; }
            set {
                if (value == null)
                    _UniqueValuesFromMasterQVWColumns = new List<NVPair>();
                else
                    _UniqueValuesFromMasterQVWColumns = value; }
        }

        /// <summary>
        /// for each NVPair item,  look up the column name (FieldName) in the data created
        /// from partial reload on REDUCED QVW, and for all the items in that column create a list of all
        /// the unique values in that column - write output back to (Value) field specified file
        /// items in list should be tilde delimited '~'.  
        private List<NVPair> _UniqueValuesFromReducedQVWColumns;

        public List<NVPair> UniqueValuesFromReducedQVWColumns {
            get { return _UniqueValuesFromReducedQVWColumns; }
            set {
                if (value == null)
                    _UniqueValuesFromReducedQVWColumns = new List<NVPair>();
                else
                    _UniqueValuesFromReducedQVWColumns = value; }
        }

        private string _DataModelFile;
        /// <summary>
        /// INPUT:if populated, save a data model file to name provided ( caller must ensure unique )
        /// </summary>
        public string DataModelFile {
            get { return _DataModelFile; }
            set { _DataModelFile = value; }
        }
    }
}
