//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milliman.Reduction.ClientApp.ReductionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReductionService.IReductionService")]
    public interface IReductionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReductionService/EnqueueReductionFolder", ReplyAction="http://tempuri.org/IReductionService/EnqueueReductionFolderResponse")]
        void EnqueueReductionFolder(string folderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReductionService/EnqueueReductionFolder", ReplyAction="http://tempuri.org/IReductionService/EnqueueReductionFolderResponse")]
        System.Threading.Tasks.Task EnqueueReductionFolderAsync(string folderPath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReductionServiceChannel : Milliman.Reduction.ClientApp.ReductionService.IReductionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReductionServiceClient : System.ServiceModel.ClientBase<Milliman.Reduction.ClientApp.ReductionService.IReductionService>, Milliman.Reduction.ClientApp.ReductionService.IReductionService {
        
        public ReductionServiceClient() {
        }
        
        public ReductionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReductionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReductionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReductionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EnqueueReductionFolder(string folderPath) {
            base.Channel.EnqueueReductionFolder(folderPath);
        }
        
        public System.Threading.Tasks.Task EnqueueReductionFolderAsync(string folderPath) {
            return base.Channel.EnqueueReductionFolderAsync(folderPath);
        }
    }
}
